"use client";
import { FormEvent,useEffect,useState } from "react";
import AdminSidebar from "./AdminSidebar";
import AdminFaqEditor from "./AdminFaqEditor";
import { loadCategories,loadProductFaq,loadProducts,saveCategories,saveProductFaq,saveProducts,StoreProduct,ProductVariation } from "../productStore";

export default function AdminProductTools({mode}:{mode:"categories"|"variations"|"faq"}){
  const [products,setProducts]=useState<StoreProduct[]>([]),[categories,setCategories]=useState<string[]>([]);
  const [selected,setSelected]=useState(""),[variations,setVariations]=useState<ProductVariation[]>([]),[faq,setFaq]=useState(""),[notice,setNotice]=useState("");
  useEffect(()=>{const all=loadProducts();setProducts(all);setCategories(loadCategories(all));setFaq(loadProductFaq());if(all[0]){setSelected(all[0].id);setVariations(all[0].variations)}},[]);
  function choose(id:string){setSelected(id);const p=products.find(x=>x.id===id);setVariations(p?.variations||[]);setNotice("")}
  function saveProduct(update:Partial<StoreProduct>){const next=products.map(x=>x.id===selected?{...x,...update}:x);setProducts(next);saveProducts(next);setNotice("Changes saved and connected to the storefront.")}
  function addCategory(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get("category")||"").trim();if(!name||categories.includes(name))return;const next=[...categories,name];setCategories(next);saveCategories(next);e.currentTarget.reset();setNotice(`${name} category added.`)}
  function renameCategory(old:string,value:string){const name=value.trim();if(!name)return;const cats=categories.map(x=>x===old?name:x);const next=products.map(p=>p.category===old?{...p,category:name}:p);setCategories(cats);setProducts(next);saveCategories(cats);saveProducts(next);setNotice("Category and connected products updated.")}
  function removeCategory(name:string){if(!confirm(`Delete ${name}? Products in this category will move to Uncategorized.`))return;const cats=categories.filter(x=>x!==name);const next=products.map(p=>p.category===name?{...p,category:"Uncategorized"}:p);if(!cats.includes("Uncategorized"))cats.push("Uncategorized");setCategories(cats);setProducts(next);saveCategories(cats);saveProducts(next);setNotice(`${name} removed.`)}
  const meta=mode==="categories"?["Product organization","Categories","Create, rename and remove storefront product categories."]:mode==="variations"?["Pricing management","Product Variations","Manage site packages and prices for every product."]:["Product content","Product FAQ","Manage product-specific questions and answers."];
  return <main className="admin-root"><AdminSidebar active="products"/><section className="admin-workspace"><header className="admin-topbar"><label><span>⌕</span><input placeholder="Search products..." /></label><div><span className="admin-top-user">M</span><b>Mehedi Rahat</b></div></header><div className="admin-page-title"><div><span className="eyebrow">{meta[0]}</span><h1>{meta[1]}</h1><p>{meta[2]}</p></div><a className="admin-export" href="/admin/products">All products →</a></div>
    {notice&&<p className="product-tool-notice">✓ {notice}</p>}
    {mode==="categories"?<section className="product-tools-layout"><div className="admin-card"><h2>Add new category</h2><form className="category-add-form" onSubmit={addCategory}><label><span>Category name</span><input name="category" required placeholder="e.g. Page Builder"/></label><button>Add category +</button></form></div><div className="admin-card category-manager"><div className="tool-card-head"><h2>All categories</h2><span>{categories.length} categories</span></div>{categories.map(cat=><div className="category-row" key={cat}><input defaultValue={cat} onBlur={e=>e.target.value!==cat&&renameCategory(cat,e.target.value)}/><span>{products.filter(p=>p.category===cat).length} products</span><button onClick={()=>removeCategory(cat)}>Delete</button></div>)}</div></section>:
      <section className="admin-card product-tool-editor"><div className="tool-card-head"><div><h2>{mode==="variations"?"Select a product to edit pricing":"Global Product FAQ"}</h2><p>{mode==="variations"?"Changes update the selected Product Details page immediately.":"This FAQ automatically appears on every Product Details page."}</p></div>{mode==="variations"&&<select value={selected} onChange={e=>choose(e.target.value)}>{products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select>}</div>
      {mode==="variations"?<><div className="information-editor variation-tool-list">{variations.map((v,i)=><div key={i}><input value={v.label} onChange={e=>setVariations(variations.map((x,j)=>j===i?{...x,label:e.target.value}:x))}/><input type="number" min="0" value={v.price} onChange={e=>setVariations(variations.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x))}/><button onClick={()=>setVariations(variations.filter((_,j)=>j!==i))}>×</button></div>)}</div><div className="product-tool-actions"><button className="add-row-button" onClick={()=>setVariations([...variations,{label:"New variation",price:0}])}>+ Add variation</button><button className="publish-product" onClick={()=>saveProduct({variations,price:variations[0]?.price||0})}>Save variations</button></div></>:
      <AdminFaqEditor value={faq} onChange={setFaq} saveLabel="Save Product FAQ" onSave={()=>{saveProductFaq(faq);setNotice("Global Product FAQ saved for every product page.")}}/>}
    </section>}</section></main>
}
