"use client";

import { useEffect, useState } from "react";
import AdminSidebar from "./AdminSidebar";
import {loadServices} from "../serviceStore";
import {loadProjects} from "../projectStore";
const sections=[["MAIN",[["▦","Dashboard","/admin"],["⌘","CRM Dashboard","/admin"]]],["CUSTOMERS",[["♙","Customers","#customers"],["▣","Orders","/admin/orders"],["♛","Membership","#membership"]]],["OPERATIONS",[["⚙","Activation Requests","#activation"],["▰","Support Tickets","#support"]]],["BUSINESS",[["◇","Products","/admin/products"],["◉","Announcements","#announcements"],["▤","Reports","#reports"],["✉","Email Campaigns","#email"]]],["SYSTEM",[["⚙","Settings","#settings"],["♙","Users","#users"],["⌘","Tools","#tools"]]]];
const products=[["Elementor Pro","13","৳ 6,100","10","17"],["CartFlows Pro","7","৳ 3,800","2","4"],["Crocoblock","4","৳ 2,400","4","2"],["Pixel Your Site Pro","2","৳ 1,320","1","0"],["Astra Pro","2","৳ 800","1","2"]];
const monthlyRevenue=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10185,0,0,29773];
export default function AdminOverview(){
 const[serviceStats,setServiceStats]=useState({total:8,published:8}),[projectStats,setProjectStats]=useState({total:2,published:2});
 useEffect(()=>{const services=loadServices(),projects=loadProjects();setServiceStats({total:services.length,published:services.filter(x=>x.status==="Published").length});setProjectStats({total:projects.length,published:projects.filter(x=>x.status==="Published").length})},[]);
 const contentSummary=[["▤","Pages","8","6 published · 2 draft","#pages"],["✎","Blog Posts","12","10 published · 2 draft","#posts"],["◇","Products","15","14 published · 1 draft","/admin/products"],["▣","Ready Themes","6","5 published · 1 draft","/admin/themes"],["⚒","Services",String(serviceStats.total),`${serviceStats.published} published · ${serviceStats.total-serviceStats.published} draft`,"/admin/services"],["◆","My Projects",String(projectStats.total),`${projectStats.published} published · ${projectStats.total-projectStats.published} draft`,"/admin/projects"]];
 return <main className="admin-root crm-admin"><AdminSidebar active="overview"/><aside className="legacy-admin-sidebar"><a className="admin-brand" href="/admin"><span>MR</span><div><b>MEHEDI RAHAT</b><small>ADMIN PANEL</small></div></a><div className="admin-owner"><span>M</span><div><small>Signed in as</small><b>Mehedi Rahat</b><em>● Administrator</em></div></div>{sections.map(([group,items])=><div className="crm-menu-group" key={String(group)}><small>{group as string}</small><nav>{(items as string[][]).map(([ic,label,url])=><a className={label==="CRM Dashboard"?"active":""} href={url} key={label}><i>{ic}</i><span>{label}</span></a>)}</nav></div>)}<div className="crm-quick"><b>⚡ Quick Actions</b><a href="#customer">♙ Add New Customer →</a><a href="#announcement">▰ Create Announcement →</a><a href="#email">✉ Send Email →</a></div></aside><section className="admin-workspace crm-workspace"><header className="admin-topbar"><label><span>⌕</span><input placeholder="Search orders, customers, tickets..." /></label><div><button>♟</button><span className="admin-top-user">M</span><b>Mehedi Rahat</b></div></header>
 <section className="crm-welcome"><div><span>WELCOME</span><h1>Good morning, Mehedi Rahat 👋</h1><p>Here is a clear snapshot of your sales, customers, operations and recent activity.</p></div><time><small>MONDAY</small><b>Jul 27, 2026</b></time></section>
 <SectionTitle eyebrow="Website overview" title="Content & publishing" note="Manage every important part of your website from one dashboard."/><div className="crm-content-grid">{contentSummary.map((x,i)=><a className={`content-tone-${i}`} href={x[4]} key={x[1]}><i>{x[0]}</i><div><span>{x[1]}</span><strong>{x[2]}</strong><small>{x[3]}</small></div><b>Manage →</b></a>)}</div>
 <SectionTitle eyebrow="Sales analytics" title="Revenue performance" note="Today, this week, this month and lifetime sales."/><div className="crm-sales-grid">{[["▣","Today's Sales","৳ 1,019","1 completed order today"],["↗","This Week's Sales","৳ 2,486","3 completed orders this week"],["▤","This Month's Sales","৳ 29,773","30 completed orders this month"],["♛","Lifetime Sales","৳ 39,958","31 completed orders overall"]].map((x,i)=><article className={`crm-tone-${i}`} key={x[1]}><i>{x[0]}</i><span>{x[1]}</span><strong>{x[2]}</strong><small>{x[3]}</small></article>)}</div>
 <SectionTitle eyebrow="Customers" title="Membership overview" link="View all customers →"/><div className="crm-member-grid">{[["♙","Silver Members","17","100.0% of customers"],["◉","Gold Members","0","0.0% of customers"],["◆","Diamond Members","0","0.0% of customers"],["♛","VIP Members","0","0.0% of customers"]].map((x,i)=><article className={`crm-member-${i}`} key={x[1]}><i>{x[0]}</i><div><b>{x[1]}</b><strong>{x[2]}</strong><small>{x[3]}</small></div></article>)}</div>
 <SectionTitle eyebrow="Operations" title="Activation & support" note="Monitor requests and customer service workload."/><div className="crm-operation-grid"><Operation title="Activation Requests" icon="⚙" total={1} labels={[["Pending","0"],["In Progress","0"],["Completed","1"]]}/><Operation title="Support Tickets" icon="◉" total={0} labels={[["Open","0"],["Waiting Reply","0"],["Closed","0"]]}/></div>
 <SectionTitle eyebrow="Top customers" title="Customer leaderboard" note="Your three highest-spending customers."/><section className="crm-white-panel"><div className="crm-panel-title"><h2>🏆 Top Customers</h2><a>View all customers →</a></div><div className="customer-table">{[["TOP 1","Maruf Ahmed","5 Orders","৳ 12,549","Gold"],["TOP 2","Rifat Arannya","2 Orders","৳ 2,500","Silver"],["TOP 3","shafi013","1 Order","৳ 2,296","Silver"]].map((x,i)=><div className={`customer-rank rank-${i}`} key={x[1]}><i>{x[0]}</i><span className="rank-avatar">{x[1].charAt(0)}</span><b>{x[1]}</b><span>{x[2]}</span><strong>{x[3]}</strong><em>{x[4]}</em><button>View Profile</button></div>)}</div></section>
 <SectionTitle eyebrow="Lifetime analytics" title="Lifetime best-selling products" note="Your strongest products across all paid orders."/><section className="crm-white-panel"><div className="crm-panel-title"><h2>🏆 Lifetime Top Selling Products</h2><a>View all products →</a></div><div className="best-products">{products.map((x,i)=><div key={x[0]}><i>#{i+1}</i><span className="product-mini">{x[0].charAt(0)}</span><b>{x[0]}<small>{i===0?"2 Variations":"1 Variation"}</small></b><Metric label="Lifetime sold" value={x[1]}/><Metric label="Lifetime revenue" value={x[2]}/><Metric label="Customers" value={x[3]}/><Metric label="Active domains" value={x[4]}/></div>)}</div></section>
 <SectionTitle eyebrow="Revenue analytics" title="Three-year selling growth" note="Monthly performance across the last 36 months."/><section className="crm-white-panel crm-growth"><div className="crm-panel-title"><h2>📈 Selling Growth — Last 36 Months</h2><div><Metric label="36-month revenue" value="৳ 39,958"/><Metric label="Monthly average" value="৳ 1,110"/><Metric label="Highest month" value="Jul 2026"/></div></div><div className="growth-chart">{monthlyRevenue.map((revenue,i)=><span key={i} style={{height:`${Math.max(2,(revenue/29773)*70)}%`}} title={`${["Aug","Sep","Oct","Nov","Dec","Jan","Feb","Mar","Apr","May","Jun","Jul"][i%12]} ${2023+Math.floor((i+7)/12)} · ৳ ${revenue.toLocaleString("en-US")}`}><small>{["Aug","Sep","Oct","Nov","Dec","Jan","Feb","Mar","Apr","May","Jun","Jul"][i%12]}</small><b className="growth-year">{2023+Math.floor((i+7)/12)}</b><em>৳{revenue.toLocaleString("en-US")}</em></span>)}</div></section>
 <SectionTitle eyebrow="Quick actions" title="Move faster" note="Jump directly to the most-used CRM actions."/><div className="crm-bottom-actions">{[["♙","Add Customer","Create a new customer account."],["▣","Manage Orders","Review orders and purchases."],["⚿","Activation Requests","Review and update requests."],["▰","Support Tickets","Open the support desk."]].map(x=><a href={x[1]==="Manage Orders"?"/admin/orders":"#"} key={x[1]}><i>{x[0]}</i><div><b>{x[1]}</b><small>{x[2]}</small></div><span>→</span></a>)}</div><footer className="crm-copy">© 2026 Mehedi Rahat · Admin CRM</footer></section></main>
}
function SectionTitle({eyebrow,title,note,link}:{eyebrow:string;title:string;note?:string;link?:string}){return <div className="crm-section-title"><div><span>{eyebrow}</span><h2>{title}</h2></div>{note&&<p>{note}</p>}{link&&<a>{link}</a>}</div>}
function Operation({title,icon,total,labels}:{title:string;icon:string;total:number;labels:string[][]}){return <article><div className="crm-panel-title"><h2>{title}</h2><b>{total}</b></div><div className="operation-body"><i>{icon}</i><strong>{total}<small>Total Requests</small></strong><div>{labels.map(x=><span key={x[0]}><b>● {x[0]}</b><em>{x[1]}</em></span>)}</div></div><a>View All {title} →</a></article>}
function Metric({label,value}:{label:string;value:string}){return <span className="crm-metric"><small>{label}</small><strong>{value}</strong></span>}
