"use client";
import {FormEvent,ReactNode,useEffect,useMemo,useState} from "react";
import AdminSidebar from "./AdminSidebar";
import {loadProjects,saveProjects,slugify,StoreProject} from "../projectStore";

export default function AdminProjects({mode}:{mode:"list"|"new"|"edit"}){
  const[projects,setProjects]=useState<StoreProject[]>([]),[editing,setEditing]=useState<StoreProject|null>(null);
  const[query,setQuery]=useState(""),[status,setStatus]=useState("All status"),[image,setImage]=useState(""),[imageName,setImageName]=useState(""),[message,setMessage]=useState("");
  useEffect(()=>{const all=loadProjects();setProjects(all);if(mode==="edit"){const id=new URLSearchParams(window.location.search).get("id");const project=all.find(x=>x.id===id)||all[0]||null;setEditing(project);if(project){setImage(project.image||"");setImageName(project.imageName||"")}}},[mode]);
  const visible=useMemo(()=>projects.filter(x=>(!query||`${x.title} ${x.category} ${x.description}`.toLowerCase().includes(query.toLowerCase()))&&(status==="All status"||x.status===status)),[projects,query,status]);
  function persist(next:StoreProject[]){const ordered=[...next].sort((a,b)=>a.order-b.order).map((x,i)=>({...x,order:i+1}));setProjects(ordered);saveProjects(ordered)}
  function move(id:string,direction:-1|1){const next=[...projects],index=next.findIndex(x=>x.id===id),target=index+direction;if(index<0||target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];persist(next)}
  function remove(project:StoreProject){if(confirm(`Delete ${project.title}?`))persist(projects.filter(x=>x.id!==project.id))}
  function upload(file?:File){if(!file)return;if(file.size>1.5*1024*1024){setMessage("Image must be smaller than 1.5 MB.");return}const reader=new FileReader();reader.onload=()=>{setImage(String(reader.result));setImageName(file.name);setMessage("")};reader.readAsDataURL(file)}
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),title=String(data.get("title")||"");const project:StoreProject={id:editing?.id||slugify(title),title,category:String(data.get("category")||""),description:String(data.get("description")||""),status:String(data.get("status")) as StoreProject["status"],order:editing?.order||projects.length+1,link:String(data.get("link")||"#support"),linkLabel:String(data.get("linkLabel")||"View project"),availability:String(data.get("availability")) as StoreProject["availability"],projectType:String(data.get("projectType")||"WordPress Plugin"),image,imageName};persist(mode==="edit"?projects.map(x=>x.id===editing?.id?project:x):[...projects,project]);setEditing(project);setMessage(`${project.title} saved and connected to the Homepage.`)}
  return <main className="admin-root"><AdminSidebar active="projects"/><section className="admin-workspace"><AdminTop/>
    {mode==="list"?<><div className="admin-page-title"><div><span className="eyebrow">Portfolio management</span><h1>My Projects</h1><p>Manage the exclusive work and products showcased on your Homepage.</p></div><a href="/admin/projects/new">Add new project +</a></div>
      <section className="product-admin-stats">{[["All projects",projects.length],["Published",projects.filter(x=>x.status==="Published").length],["Drafts",projects.filter(x=>x.status==="Draft").length],["Homepage positions",projects.length]].map(item=><article key={String(item[0])}><span>{item[0]}</span><strong>{item[1]}</strong></article>)}</section>
      <section className="admin-card product-list-card"><div className="product-toolbar"><label>⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects..."/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option>All status</option><option>Published</option><option>Draft</option></select></div>
        <div className="project-admin-grid">{visible.map(project=><article key={project.id}><div className="project-admin-image">{project.image?<img src={project.image} alt=""/>:<><span/><span/><i/><i/><i/></>}</div><div className="project-admin-copy"><span>{String(project.order).padStart(2,"0")} / {project.category}</span><div className="admin-project-labels"><b>{project.projectType}</b><i className={project.availability==="Live Now"?"live":"soon"}>{project.availability}</i></div><h2>{project.title}</h2><p>{project.description}</p><div><em className={project.status.toLowerCase()}>{project.status}</em><span className="service-order-actions"><button onClick={()=>move(project.id,-1)}>↑</button><button onClick={()=>move(project.id,1)}>↓</button></span><span className="product-row-actions"><a href="/#projects" target="_blank">View</a><a href={`/admin/projects/edit?id=${project.id}`}>Edit</a><button onClick={()=>remove(project)}>×</button></span></div></div></article>)}</div>
      </section></>:
      <><div className="admin-page-title"><div><span className="eyebrow">My Projects</span><h1>{mode==="new"?"Add Project":"Edit Project"}</h1><p>Configure the project content, featured image, link and visibility.</p></div><a className="admin-export" href="/admin/projects">Back to projects →</a></div>
        <form className="product-editor" onSubmit={submit}><div className="product-editor-main"><EditorCard title="Project information"><div className="editor-grid"><Field label="Project title"><input name="title" required defaultValue={editing?.title}/></Field><Field label="Project category"><input name="category" required defaultValue={editing?.category} placeholder="WooCommerce Solution"/></Field><Field label="Project type"><input name="projectType" required defaultValue={editing?.projectType||"WordPress Plugin"}/></Field><Field label="Homepage status button"><select name="availability" defaultValue={editing?.availability||"Live Now"}><option>Live Now</option><option>Coming Soon</option></select></Field><Field label="Publish status"><select name="status" defaultValue={editing?.status||"Published"}><option>Published</option><option>Draft</option></select></Field><Field label="Project URL (used for Live Now)"><input name="link" defaultValue={editing?.link||"#support"} placeholder="https://... or #support"/></Field><input name="linkLabel" type="hidden" value={editing?.linkLabel||"View project"}/></div><Field label="Project description"><textarea name="description" required defaultValue={editing?.description} placeholder="Describe the project and its practical value..."/></Field></EditorCard>
          <EditorCard title="Homepage preview"><article className="work-card project-editor-preview"><div className={`work-preview${image?" has-project-image":""}`}>{image?<img src={image} alt="Preview"/>:<><span className="preview-top"><i/><i/><i/></span><span className="preview-copy"><b/><b/><small/></span><span className="preview-panels"><i/><i/><i/></span></>}</div><div className="work-copy"><span>{editing?.category||"Project category"}</span><div className="project-type-label"><i>WP</i>{editing?.projectType||"WordPress Plugin"}</div><h3>{editing?.title||"Your project title"}</h3><p>{editing?.description||"Your project description will appear here."}</p><span className={`project-status-button ${(editing?.availability||"Live Now")==="Live Now"?"live":"soon"}`}>{editing?.availability||"Live Now"} ↗</span></div></article></EditorCard>
        </div><aside className="product-editor-side"><EditorCard title="Featured image"><label className="image-upload-placeholder">{image?<img src={image} alt="Project preview"/>:<><i>◇</i><b>Upload project image</b><small>PNG, JPG or WebP · max 1.5 MB</small></>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0])}/><span>{imageName||"Choose image"}</span></label>{image&&<button className="remove-service-image" type="button" onClick={()=>{setImage("");setImageName("")}}>Remove image</button>}</EditorCard>{message&&<p className="editor-saved">✓ {message}</p>}<button className="publish-product" type="submit">{mode==="new"?"Save & Publish Project":"Update Project"} ↗</button><a className="save-draft service-cancel" href="/admin/projects">Cancel</a></aside></form></>}
  </section></main>
}
function AdminTop(){return <header className="admin-topbar"><label><span>⌕</span><input placeholder="Search projects, services, products..."/></label><div><button>♟</button><span className="admin-top-user">M</span><b>Mehedi Rahat</b></div></header>}
function EditorCard({title,children}:{title:string;children:ReactNode}){return <section className="admin-card editor-card"><h2>{title}</h2>{children}</section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="editor-field"><span>{label}</span>{children}</label>}
