"use client";
import {useEffect,useState} from "react";
import AdminSidebar from "./AdminSidebar";
import {HomepageSettings,loadHomepageSettings,saveHomepageSettings,seedHomepageSettings} from "../homepageStore";
export default function AdminHomepage(){
 const[data,setData]=useState<HomepageSettings>(seedHomepageSettings),[message,setMessage]=useState("");
 useEffect(()=>setData(loadHomepageSettings()),[]);
 const set=<K extends keyof HomepageSettings>(key:K,value:HomepageSettings[K])=>setData(current=>({...current,[key]:value}));
 const stat=(index:number,key:"value"|"label",value:string)=>setData(current=>({...current,stats:current.stats.map((item,i)=>i===index?{...item,[key]:value}:item)}));
 const cardItem=(index:number,key:"title"|"description"|"url",value:string)=>setData(current=>({...current,heroCardItems:current.heroCardItems.map((item,i)=>i===index?{...item,[key]:value}:item)}));
 const proof=(index:number,key:"value"|"label",value:string)=>setData(current=>({...current,heroProofs:current.heroProofs.map((item,i)=>i===index?{...item,[key]:value}:item)}));
 const save=()=>{saveHomepageSettings(data);setMessage("Homepage settings saved and connected to the live Homepage.")};
 const reset=()=>{setData(seedHomepageSettings);saveHomepageSettings(seedHomepageSettings);setMessage("Default Homepage content restored.")};
 return <main className="admin-root"><AdminSidebar active="pages"/><section className="admin-workspace"><AdminTop/>
 <div className="admin-page-title"><div><span className="eyebrow">Website content</span><h1>Homepage Management</h1><p>Manage the main Hero and important Homepage section headings from one place.</p></div><a href="/" target="_blank">View Homepage ↗</a></div>
 <div className="homepage-editor-layout"><div className="homepage-editor-main">
 <section className="admin-card editor-card"><h2>Hero content</h2><div className="editor-grid"><Field label="Eyebrow text"><input value={data.heroEyebrow} onChange={e=>set("heroEyebrow",e.target.value)}/></Field><Field label="Headline line 1"><input value={data.heroLine1} onChange={e=>set("heroLine1",e.target.value)}/></Field><Field label="Headline line 2"><input value={data.heroLine2} onChange={e=>set("heroLine2",e.target.value)}/></Field><Field label="Line 2 highlighted word"><input value={data.heroLine2Highlight} onChange={e=>set("heroLine2Highlight",e.target.value)}/></Field><Field label="Headline line 3 (highlighted)"><input value={data.heroLine3Highlight} onChange={e=>set("heroLine3Highlight",e.target.value)}/></Field></div><Field label="Hero description (shown after Mehedi Rahat)"><textarea value={data.heroDescription} onChange={e=>set("heroDescription",e.target.value)}/></Field></section>
 <section className="admin-card editor-card"><h2>Buttons & statistics</h2><div className="editor-grid"><Field label="Primary button label"><input value={data.primaryLabel} onChange={e=>set("primaryLabel",e.target.value)}/></Field><Field label="Primary button link"><input value={data.primaryUrl} onChange={e=>set("primaryUrl",e.target.value)}/></Field><Field label="Secondary button label"><input value={data.secondaryLabel} onChange={e=>set("secondaryLabel",e.target.value)}/></Field><Field label="Secondary button link"><input value={data.secondaryUrl} onChange={e=>set("secondaryUrl",e.target.value)}/></Field></div><div className="homepage-stat-editor">{data.stats.slice(0,3).map((item,index)=><div key={index}><b>Statistic {index+1}</b><input value={item.value} onChange={e=>stat(index,"value",e.target.value)}/><input value={item.label} onChange={e=>stat(index,"label",e.target.value)}/></div>)}</div></section>
 <section className="admin-card editor-card"><h2>Hero right-side card</h2><div className="editor-grid"><Field label="Small heading"><input value={data.heroCardEyebrow} onChange={e=>set("heroCardEyebrow",e.target.value)}/></Field><Field label="Main heading"><input value={data.heroCardTitle} onChange={e=>set("heroCardTitle",e.target.value)}/></Field><Field label="Highlighted heading"><input value={data.heroCardHighlight} onChange={e=>set("heroCardHighlight",e.target.value)}/></Field></div><div className="hero-card-item-editor">{data.heroCardItems.slice(0,3).map((item,index)=><div key={index}><b>Item {index+1}</b><input value={item.title} onChange={e=>cardItem(index,"title",e.target.value)} placeholder="Title"/><input value={item.description} onChange={e=>cardItem(index,"description",e.target.value)} placeholder="Description"/><input value={item.url} onChange={e=>cardItem(index,"url",e.target.value)} placeholder="/page-link"/></div>)}</div><div className="homepage-stat-editor homepage-proof-editor">{data.heroProofs.slice(0,2).map((item,index)=><div key={index}><b>Proof {index+1}</b><input value={item.value} onChange={e=>proof(index,"value",e.target.value)}/><input value={item.label} onChange={e=>proof(index,"label",e.target.value)}/></div>)}</div></section>
 <SectionEditor title="Services section" visible={data.servicesVisible} onVisible={v=>set("servicesVisible",v)} eyebrow={data.servicesEyebrow} setEyebrow={v=>set("servicesEyebrow",v)} heading={data.servicesTitle} setHeading={v=>set("servicesTitle",v)} highlight={data.servicesHighlight} setHighlight={v=>set("servicesHighlight",v)} linkLabel={data.servicesLinkLabel} setLinkLabel={v=>set("servicesLinkLabel",v)} linkUrl={data.servicesLinkUrl} setLinkUrl={v=>set("servicesLinkUrl",v)}/>
 <SectionEditor title="My Projects section" visible={data.projectsVisible} onVisible={v=>set("projectsVisible",v)} eyebrow={data.projectsEyebrow} setEyebrow={v=>set("projectsEyebrow",v)} heading={data.projectsTitle} setHeading={v=>set("projectsTitle",v)} highlight={data.projectsHighlight} setHighlight={v=>set("projectsHighlight",v)} linkLabel={data.projectsLinkLabel} setLinkLabel={v=>set("projectsLinkLabel",v)} linkUrl={data.projectsLinkUrl} setLinkUrl={v=>set("projectsLinkUrl",v)}/>
 <SectionEditor title="Client Feedback section" visible={data.reviewsVisible} onVisible={v=>set("reviewsVisible",v)} eyebrow={data.reviewsEyebrow} setEyebrow={v=>set("reviewsEyebrow",v)} heading={data.reviewsTitle} setHeading={v=>set("reviewsTitle",v)} highlight={data.reviewsHighlight} setHighlight={v=>set("reviewsHighlight",v)}/>
 </div><aside className="homepage-editor-side"><section className="admin-card homepage-status-card"><span className="eyebrow">Homepage status</span><h2>Ready to update</h2><p>Your saved content appears on the Homepage immediately.</p><ul><li>Hero content</li><li>Buttons and statistics</li><li>Section headings</li><li>Section visibility</li></ul></section>{message&&<p className="editor-saved">✓ {message}</p>}<button className="publish-product" onClick={save}>Save Homepage Changes ↗</button><button className="save-draft" onClick={reset}>Restore default content</button></aside></div>
 </section></main>
}
function AdminTop(){return <header className="admin-topbar"><label><span>⌕</span><input placeholder="Search Homepage settings..."/></label><div><button>♟</button><span className="admin-top-user">M</span><b>Mehedi Rahat</b></div></header>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="editor-field"><span>{label}</span>{children}</label>}
function SectionEditor(p:{title:string;visible:boolean;onVisible:(v:boolean)=>void;eyebrow:string;setEyebrow:(v:string)=>void;heading:string;setHeading:(v:string)=>void;highlight:string;setHighlight:(v:string)=>void;linkLabel?:string;setLinkLabel?:(v:string)=>void;linkUrl?:string;setLinkUrl?:(v:string)=>void}){return <section className="admin-card editor-card homepage-section-editor"><div className="homepage-editor-heading"><h2>{p.title}</h2><label><input type="checkbox" checked={p.visible} onChange={e=>p.onVisible(e.target.checked)}/> Show on Homepage</label></div><div className="editor-grid"><Field label="Eyebrow"><input value={p.eyebrow} onChange={e=>p.setEyebrow(e.target.value)}/></Field><Field label="Heading"><input value={p.heading} onChange={e=>p.setHeading(e.target.value)}/></Field><Field label="Highlighted heading"><input value={p.highlight} onChange={e=>p.setHighlight(e.target.value)}/></Field>{p.setLinkLabel&&<Field label="Link label"><input value={p.linkLabel} onChange={e=>p.setLinkLabel?.(e.target.value)}/></Field>}{p.setLinkUrl&&<Field label="Link URL"><input value={p.linkUrl} onChange={e=>p.setLinkUrl?.(e.target.value)}/></Field>}</div></section>}
