"use client";
import {useEffect,useState} from "react";
import AdminSidebar from "./AdminSidebar";
import {ServicesPageSettings,loadServicesPageSettings,saveServicesPageSettings,seedServicesPageSettings} from "../servicesPageStore";

export default function AdminServicesPage(){
 const[data,setData]=useState<ServicesPageSettings>(seedServicesPageSettings),[message,setMessage]=useState("");
 useEffect(()=>setData(loadServicesPageSettings()),[]);
 const set=<K extends keyof ServicesPageSettings>(key:K,value:ServicesPageSettings[K])=>setData(c=>({...c,[key]:value}));
 const item=(key:"stats"|"capabilities"|"packages"|"gigs",index:number,field:string,value:string|boolean|string[])=>setData(c=>{
  const current:readonly unknown[]=c[key];
  const updated=current.map((entry,i)=>i===index&&typeof entry==="object"&&entry!==null?{...entry,[field]:value}:entry);
  return {...c,[key]:updated} as ServicesPageSettings;
 });
 const save=()=>{saveServicesPageSettings(data);setMessage("Services Page saved and connected to the live page.")};
 return <main className="admin-root"><AdminSidebar active="pages"/><section className="admin-workspace"><Top/>
  <div className="admin-page-title"><div><span className="eyebrow">Website content</span><h1>Services Page Management</h1><p>Edit the complete Services Page from one place.</p></div><a href="/services" target="_blank">View Services Page ↗</a></div>
  <div className="homepage-editor-layout"><div className="homepage-editor-main">
   <Card title="Hero section" visible={data.heroVisible} toggle={v=>set("heroVisible",v)}>
    <div className="editor-grid"><Field label="Eyebrow"><input value={data.heroEyebrow} onChange={e=>set("heroEyebrow",e.target.value)}/></Field>{data.heroLines.slice(0,3).map((x,i)=><Field key={i} label={`Headline line ${i+1}${i===2?" (highlighted)":""}`}><input value={x} onChange={e=>set("heroLines",data.heroLines.map((v,n)=>n===i?e.target.value:v))}/></Field>)}</div>
    <Field label="Description"><textarea value={data.heroDescription} onChange={e=>set("heroDescription",e.target.value)}/></Field>
    <div className="editor-grid"><Field label="Primary button label"><input value={data.primaryLabel} onChange={e=>set("primaryLabel",e.target.value)}/></Field><Field label="Primary button URL"><input value={data.primaryUrl} onChange={e=>set("primaryUrl",e.target.value)}/></Field><Field label="Secondary button label"><input value={data.secondaryLabel} onChange={e=>set("secondaryLabel",e.target.value)}/></Field><Field label="Secondary button URL"><input value={data.secondaryUrl} onChange={e=>set("secondaryUrl",e.target.value)}/></Field></div>
    <div className="homepage-stat-editor">{data.stats.slice(0,3).map((x,i)=><div key={i}><b>Statistic {i+1}</b><input value={x.value} onChange={e=>item("stats",i,"value",e.target.value)}/><input value={x.label} onChange={e=>item("stats",i,"label",e.target.value)}/></div>)}</div>
   </Card>
   <Card title="Hero right-side panel">
    <div className="editor-grid"><Field label="Eyebrow"><input value={data.panelEyebrow} onChange={e=>set("panelEyebrow",e.target.value)}/></Field>{data.panelLines.slice(0,2).map((x,i)=><Field key={i} label={`Heading line ${i+1}`}><input value={x} onChange={e=>set("panelLines",data.panelLines.map((v,n)=>n===i?e.target.value:v))}/></Field>)}<Field label="Badge value"><input value={data.panelBadgeValue} onChange={e=>set("panelBadgeValue",e.target.value)}/></Field><Field label="Badge label"><input value={data.panelBadgeLabel} onChange={e=>set("panelBadgeLabel",e.target.value)}/></Field></div>
    <div className="services-admin-repeat">{data.capabilities.slice(0,4).map((x,i)=><div key={i}><b>Capability {i+1}</b><input value={x.title} onChange={e=>item("capabilities",i,"title",e.target.value)} placeholder="Title"/><input value={x.description} onChange={e=>item("capabilities",i,"description",e.target.value)} placeholder="Description"/><input value={x.url} onChange={e=>item("capabilities",i,"url",e.target.value)} placeholder="Link"/></div>)}</div>
    <Field label="Bottom proof points (one per line)"><textarea value={data.panelProofs.join("\n")} onChange={e=>set("panelProofs",lines(e.target.value))}/></Field>
   </Card>
   <Card title="Service cards" visible={data.servicesVisible} toggle={v=>set("servicesVisible",v)}><div className="services-editor-link"><div><b>Eight service cards use Services Management</b><p>Edit their title, description, icon and visibility from the existing manager.</p></div><a href="/admin/services">Open Services Management ↗</a></div></Card>
   <Card title="Service pricing" visible={data.pricingVisible} toggle={v=>set("pricingVisible",v)}>
    <div className="editor-grid"><Field label="Eyebrow"><input value={data.pricingEyebrow} onChange={e=>set("pricingEyebrow",e.target.value)}/></Field><Field label="Heading"><input value={data.pricingTitle} onChange={e=>set("pricingTitle",e.target.value)}/></Field><Field label="Highlighted heading"><input value={data.pricingHighlight} onChange={e=>set("pricingHighlight",e.target.value)}/></Field></div><Field label="Description"><textarea value={data.pricingDescription} onChange={e=>set("pricingDescription",e.target.value)}/></Field>
    <div className="services-admin-packages">{data.packages.slice(0,4).map((x,i)=><div key={i}><b>Package {i+1}</b><input value={x.name} onChange={e=>item("packages",i,"name",e.target.value)} placeholder="Name"/><div><input value={x.price} onChange={e=>item("packages",i,"price",e.target.value)} placeholder="Price"/><input value={x.note} onChange={e=>item("packages",i,"note",e.target.value)} placeholder="Price note"/></div><textarea value={x.features.join("\n")} onChange={e=>item("packages",i,"features",lines(e.target.value))}/><label><input type="radio" name="popular" checked={x.popular} onChange={()=>set("packages",data.packages.map((v,n)=>({...v,popular:n===i})))}/> Recommended package</label></div>)}</div>
   </Card>
   <Card title="Fiverr section" visible={data.fiverrVisible} toggle={v=>set("fiverrVisible",v)}>
    <div className="editor-grid"><Field label="Eyebrow"><input value={data.fiverrEyebrow} onChange={e=>set("fiverrEyebrow",e.target.value)}/></Field><Field label="Heading"><input value={data.fiverrTitle} onChange={e=>set("fiverrTitle",e.target.value)}/></Field><Field label="Highlighted heading"><input value={data.fiverrHighlight} onChange={e=>set("fiverrHighlight",e.target.value)}/></Field><Field label="Section link label"><input value={data.fiverrLinkLabel} onChange={e=>set("fiverrLinkLabel",e.target.value)}/></Field><Field label="Section link URL"><input value={data.fiverrLinkUrl} onChange={e=>set("fiverrLinkUrl",e.target.value)}/></Field></div><Field label="Description"><textarea value={data.fiverrDescription} onChange={e=>set("fiverrDescription",e.target.value)}/></Field>
    <div className="services-admin-repeat">{data.gigs.slice(0,4).map((x,i)=><div key={i}><b>Gig {i+1}</b><input value={x.code} onChange={e=>item("gigs",i,"code",e.target.value)} placeholder="Cover label"/><input value={x.title} onChange={e=>item("gigs",i,"title",e.target.value)} placeholder="Title"/><input value={x.url} onChange={e=>item("gigs",i,"url",e.target.value)} placeholder="Link"/></div>)}</div><Field label="Shared gig benefits (one per line)"><textarea value={data.gigBenefits.join("\n")} onChange={e=>set("gigBenefits",lines(e.target.value))}/></Field>
   </Card>
  </div><aside className="homepage-editor-side"><section className="admin-card homepage-status-card"><span className="eyebrow">Services Page status</span><h2>Ready to update</h2><p>Saved changes appear on the Services Page immediately.</p><ul><li>Hero and right-side panel</li><li>Service section visibility</li><li>Pricing packages</li><li>Fiverr gigs and links</li></ul></section>{message&&<p className="editor-saved">✓ {message}</p>}<button className="publish-product" onClick={save}>Save Services Page ↗</button><button className="save-draft" onClick={()=>{setData(seedServicesPageSettings);saveServicesPageSettings(seedServicesPageSettings);setMessage("Default Services Page content restored.")}}>Restore default content</button></aside></div>
 </section></main>
}
const lines=(v:string)=>v.split("\n").map(x=>x.trim()).filter(Boolean);
function Top(){return <header className="admin-topbar"><label><span>⌕</span><input placeholder="Search Services Page settings..."/></label><div><button>♟</button><span className="admin-top-user">M</span><b>Mehedi Rahat</b></div></header>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="editor-field"><span>{label}</span>{children}</label>}
function Card({title,visible,toggle,children}:{title:string;visible?:boolean;toggle?:(v:boolean)=>void;children:React.ReactNode}){return <section className="admin-card editor-card homepage-section-editor"><div className="homepage-editor-heading"><h2>{title}</h2>{toggle&&<label><input type="checkbox" checked={visible} onChange={e=>toggle(e.target.checked)}/> Show on Services Page</label>}</div><div className="services-admin-card-body">{children}</div></section>}
