"use client";
import { FormEvent,ReactNode,useEffect,useMemo,useState } from "react";
import AdminSidebar from "./AdminSidebar";
import { RichTextEditor } from "./AdminProducts";
import { decodePackageFeatures,encodePackageFeatures,loadCategoryPackageFeatures,loadThemeCategories,loadThemes,ReadyTheme,saveCategoryPackageFeatures,saveThemeCategories,saveThemes,themeSlug } from "../themeStore";

export default function AdminThemes({mode}:{mode:"list"|"new"|"edit"|"categories"|"packages"}){
  const [themes,setThemes]=useState<ReadyTheme[]>([]),[editing,setEditing]=useState<ReadyTheme|null>(null);
  const [description,setDescription]=useState(""),[catalogImage,setCatalogImage]=useState(""),[catalogImageName,setCatalogImageName]=useState(""),[detailImage,setDetailImage]=useState(""),[detailImageName,setDetailImageName]=useState("");
  const [featureItems,setFeatureItems]=useState(["Responsive design","Ready inner pages","Contact form","Easy customization"]);
  const [informationItems,setInformationItems]=useState([["CMS","WordPress"],["Builder","Elementor"],["Ready pages","6"],["Responsive","Included"],["Speed ready","Included"],["SEO structure","Included"]]);
  const [packageFeatureItems,setPackageFeatureItems]=useState<[string,boolean,boolean,boolean][]>([["Unique Design",true,true,true],["Premium Theme Plugin",true,true,true],["Mobile Friendly",true,true,true],["Photo Gallery",true,true,true],["Video Gallery",true,true,true],["News Ticker",true,true,true],["Technical Support",true,true,true],["Search Optimization",false,true,true],["Speed Optimization",false,true,true],["Domain For One Year",false,false,true],["5 GB Hosting For One Year",false,false,true]]);
  const [packageMode,setPackageMode]=useState<"category"|"custom">("category");
  const [categories,setCategories]=useState<string[]>([]);
  const [query,setQuery]=useState(""),[category,setCategory]=useState("All categories"),[status,setStatus]=useState("All status"),[notice,setNotice]=useState("");
  useEffect(()=>{const all=loadThemes();setThemes(all);if(mode==="edit"){const id=new URLSearchParams(location.search).get("id");const item=all.find(x=>x.id===id)||all[0]||null;setEditing(item);if(item){setDescription(item.description);setCatalogImage(item.catalogImage||item.image||"");setCatalogImageName(item.catalogImageName||item.imageName||"");setDetailImage(item.detailImage||item.image||"");setDetailImageName(item.detailImageName||item.imageName||"");setFeatureItems(item.features.split("\n").filter(Boolean));setPackageMode(item.packageFeatureMode||"category");setPackageFeatureItems(item.packageFeatureMode==="custom"&&item.packageFeatures?decodePackageFeatures(item.packageFeatures):loadCategoryPackageFeatures(item.category));const defaults=[["CMS","WordPress"],["Builder","Elementor"],["Ready pages",String(item.pages)],["Responsive","Included"],["Speed ready","Included"],["SEO structure","Included"]];setInformationItems(item.information?item.information.split("\n").filter(Boolean).map(row=>{const at=row.indexOf("|");return at<0?[row,""]:[row.slice(0,at),row.slice(at+1)]}):defaults)}}},[mode]);
  useEffect(()=>setCategories(loadThemeCategories(themes)),[themes]);
  const visible=useMemo(()=>themes.filter(theme=>(!query||`${theme.name} ${theme.category}`.toLowerCase().includes(query.toLowerCase()))&&(category==="All categories"||theme.category===category)&&(status==="All status"||theme.status===status)),[themes,query,category,status]);
  function persist(next:ReadyTheme[]){setThemes(next);saveThemes(next)}
  async function upload(file:File|undefined,target:"catalog"|"detail"){if(!file)return;if(file.size>1.5*1024*1024){setNotice("Image must be smaller than 1.5 MB for the local prototype.");return}const data=await fileToData(file);if(target==="catalog"){setCatalogImage(data);setCatalogImageName(file.name)}else{setDetailImage(data);setDetailImageName(file.name)}}
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get("name")||"");const theme:ReadyTheme={id:editing?.id||themeSlug(name),name,category:String(f.get("category")||""),status:String(f.get("status")) as ReadyTheme["status"],price:Number(f.get("price")||0),pages:Number(f.get("pages")||0),rating:Math.min(5,Math.max(0,Number(f.get("rating")||4.9))),reviewCount:Math.max(0,Number(f.get("reviewCount")||0)),description,features:featureItems.map(item=>item.trim()).filter(Boolean).join("\n"),information:informationItems.filter(row=>row[0].trim()||row[1].trim()).map(row=>`${row[0].trim()}|${row[1].trim()}`).join("\n"),packageFeatureMode:packageMode,packageFeatures:packageMode==="custom"?encodePackageFeatures(packageFeatureItems):"",demo:String(f.get("demo")||""),catalogImage,catalogImageName,detailImage,detailImageName};persist(mode==="edit"?themes.map(x=>x.id===editing?.id?theme:x):[theme,...themes]);setNotice(`${theme.name} saved successfully.`)}
  function remove(theme:ReadyTheme){if(confirm(`Delete ${theme.name}?`))persist(themes.filter(x=>x.id!==theme.id))}
  return <main className="admin-root"><AdminSidebar active="themes"/><section className="admin-workspace"><AdminTop/>
    {mode==="list"?<><PageTitle eyebrow="Ready theme management" title="Ready Themes" text="Add, edit, publish and organize every ready-made website theme."><a href="/admin/themes/new">Add new theme +</a></PageTitle>
      <section className="product-admin-stats">{[["All themes",themes.length],["Published",themes.filter(x=>x.status==="Published").length],["Drafts",themes.filter(x=>x.status==="Draft").length],["Categories",categories.length]].map(item=><article key={String(item[0])}><span>{item[0]}</span><strong>{item[1]}</strong></article>)}</section>
      <section className="admin-card product-list-card"><div className="product-toolbar"><label>⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search themes..."/></label><select value={category} onChange={e=>setCategory(e.target.value)}><option>All categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>All status</option><option>Published</option><option>Draft</option></select></div>
      <div className="theme-admin-table"><div className="theme-table-head"><span>Theme</span><span>Category</span><span>Pages</span><span>Price</span><span>Status</span><span>Action</span></div>{visible.map(theme=><div className="theme-table-row" key={theme.id}><span className="admin-product-name">{theme.catalogImage?<img src={theme.catalogImage} alt=""/>:<i>{theme.name.charAt(0)}</i>}<b>{theme.name}<small>/{theme.id}</small></b></span><span>{theme.category}</span><span>{theme.pages} pages</span><strong>৳ {theme.price.toLocaleString("en-US")}</strong><em className={theme.status.toLowerCase()}>{theme.status}</em><span className="product-row-actions">{theme.demo&&<a href={theme.demo} target="_blank">Demo</a>}<a href={`/admin/themes/edit?id=${theme.id}`}>Edit</a><button onClick={()=>remove(theme)}>×</button></span></div>)}</div></section>
    </>:mode==="categories"?<ThemeCategories themes={themes} setThemes={persist} notice={notice} setNotice={setNotice}/>:mode==="packages"?<CategoryPackageFeatures themes={themes}/>:
    <><PageTitle eyebrow="Ready theme management" title={mode==="new"?"Add Theme":"Edit Theme"} text="Configure theme content, price, pages, preview image and live demo."><a className="admin-export" href="/admin/themes">Back to themes →</a></PageTitle>
      {notice&&<p className="product-tool-notice">✓ {notice}</p>}
      <form className="product-editor theme-editor" onSubmit={submit}><div className="product-editor-main">
        <Card title="Basic information"><div className="editor-grid"><Field label="Theme name"><input name="name" required defaultValue={editing?.name}/></Field><Field label="Category"><input name="category" list="theme-categories" required defaultValue={editing?.category}/><datalist id="theme-categories">{categories.map(x=><option value={x} key={x}/>)}</datalist></Field><Field label="Number of pages"><input name="pages" type="number" min="1" defaultValue={editing?.pages||6}/></Field><Field label="Price (BDT)"><input name="price" type="number" min="0" defaultValue={editing?.price||7500}/></Field><Field label="Rating score (0–5)"><input name="rating" type="number" min="0" max="5" step="0.1" defaultValue={editing?.rating??4.9}/></Field><Field label="Verified review count"><input name="reviewCount" type="number" min="0" step="1" defaultValue={editing?.reviewCount??5}/></Field><Field label="Publish status"><select name="status" defaultValue={editing?.status||"Published"}><option>Published</option><option>Draft</option></select></Field></div><Field label="Theme description"><RichTextEditor value={description} onChange={setDescription}/></Field></Card>
        <Card title="Purchase card features"><div className="theme-feature-editor"><div className="theme-feature-editor-head"><div><b>Highlighted features</b><span>The first four items appear beside the Add to Cart section.</span></div><em>{featureItems.length} features</em></div><div className="theme-feature-editor-list">{featureItems.map((feature,index)=><div key={index}><i>{index+1}</i><input value={feature} onChange={e=>setFeatureItems(featureItems.map((item,i)=>i===index?e.target.value:item))} placeholder={`Feature ${index+1}`}/><button type="button" aria-label={`Remove feature ${index+1}`} onClick={()=>setFeatureItems(featureItems.filter((_,i)=>i!==index))}>×</button></div>)}</div><button className="add-row-button" type="button" onClick={()=>setFeatureItems([...featureItems,""])}>+ Add feature</button></div></Card>
        <Card title="Package features"><div className="package-mode-select"><label><input type="radio" checked={packageMode==="category"} onChange={()=>setPackageMode("category")}/><span>Use category defaults</span></label><label><input type="radio" checked={packageMode==="custom"} onChange={()=>setPackageMode("custom")}/><span>Custom for this theme</span></label></div>{packageMode==="category"?<p className="package-category-note">This theme will automatically use the package matrix saved for its category.</p>:<PackageMatrix rows={packageFeatureItems} setRows={setPackageFeatureItems}/>}</Card>
        <Card title="Theme information"><div className="theme-information-editor"><div className="theme-feature-editor-head"><div><b>Information table</b><span>Each label and value appears on this theme’s Details Page.</span></div><em>{informationItems.length} rows</em></div><div className="theme-information-list">{informationItems.map((row,index)=><div key={index}><i>{index+1}</i><input value={row[0]} onChange={e=>setInformationItems(informationItems.map((item,i)=>i===index?[e.target.value,item[1]]:item))} placeholder="Label"/><input value={row[1]} onChange={e=>setInformationItems(informationItems.map((item,i)=>i===index?[item[0],e.target.value]:item))} placeholder="Value"/><button type="button" aria-label={`Remove information row ${index+1}`} onClick={()=>setInformationItems(informationItems.filter((_,i)=>i!==index))}>×</button></div>)}</div><button className="add-row-button" type="button" onClick={()=>setInformationItems([...informationItems,["",""]])}>+ Add information row</button></div></Card>
      </div><aside className="product-editor-side"><Card title="Catalog feature image"><label className="image-upload-placeholder theme-image-upload">{catalogImage?<img src={catalogImage} alt="Catalog preview"/>:<><i>◇</i><b>Upload catalog image</b><small>Shown on the Ready Themes catalog</small></>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0],"catalog")}/><span>{catalogImageName||"Choose catalog image"}</span></label></Card><Card title="Details page image"><label className="image-upload-placeholder theme-image-upload">{detailImage?<img src={detailImage} alt="Details page preview"/>:<><i>◇</i><b>Upload details image</b><small>Shown only on the Theme Details page</small></>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0],"detail")}/><span>{detailImageName||"Choose details image"}</span></label></Card><Card title="Preview link"><Field label="Live demo URL"><input name="demo" type="url" defaultValue={editing?.demo} placeholder="https://..."/></Field></Card><button className="publish-product" type="submit">{mode==="new"?"Save & Publish Theme":"Update Theme"} ↗</button><a className="save-draft theme-back-button" href="/admin/themes">Cancel</a></aside></form>
    </>}</section></main>
}

function ThemeCategories({themes,setThemes,notice,setNotice}:{themes:ReadyTheme[];setThemes:(themes:ReadyTheme[])=>void;notice:string;setNotice:(value:string)=>void}){
  const [categories,setCategories]=useState<string[]>([]);
  useEffect(()=>setCategories(loadThemeCategories(themes)),[themes]);
  function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,name=String(new FormData(form).get("category")||"").trim();if(!name||categories.includes(name))return;const next=[...categories,name];setCategories(next);saveThemeCategories(next);form.reset();setNotice(`${name} category added.`)}
  function rename(old:string,name:string){name=name.trim();if(!name)return;const cats=categories.map(x=>x===old?name:x),next=themes.map(x=>x.category===old?{...x,category:name}:x);setCategories(cats);saveThemeCategories(cats);setThemes(next);setNotice("Category and connected themes updated.")}
  function remove(name:string){if(!confirm(`Delete ${name}?`))return;const cats=categories.filter(x=>x!==name),next=themes.map(x=>x.category===name?{...x,category:"Uncategorized"}:x);if(!cats.includes("Uncategorized"))cats.push("Uncategorized");setCategories(cats);saveThemeCategories(cats);setThemes(next);setNotice(`${name} removed.`)}
  return <><PageTitle eyebrow="Ready theme organization" title="Theme Categories" text="Create, rename and organize storefront theme categories."><a className="admin-export" href="/admin/themes">All themes →</a></PageTitle>{notice&&<p className="product-tool-notice">✓ {notice}</p>}<section className="product-tools-layout"><div className="admin-card"><h2>Add new category</h2><form className="category-add-form" onSubmit={add}><label><span>Category name</span><input name="category" required placeholder="e.g. Newspaper Themes"/></label><button>Add category +</button></form></div><div className="admin-card category-manager"><div className="tool-card-head"><h2>All theme categories</h2><span>{categories.length} categories</span></div>{categories.map(cat=><div className="category-row" key={cat}><input defaultValue={cat} onBlur={e=>e.target.value!==cat&&rename(cat,e.target.value)}/><span>{themes.filter(x=>x.category===cat).length} themes</span><button onClick={()=>remove(cat)}>Delete</button></div>)}</div></section></>
}
function PackageMatrix({rows,setRows}:{rows:[string,boolean,boolean,boolean][];setRows:(rows:[string,boolean,boolean,boolean][])=>void}){
  return <div className="package-feature-editor"><div className="package-feature-head"><b>Feature</b><span>Pack 01</span><span>Pack 02</span><span>Pack 03</span><i/></div>{rows.map((row,index)=><div className="package-feature-row" key={index}><input value={row[0]} onChange={e=>setRows(rows.map((item,i)=>i===index?[e.target.value,item[1],item[2],item[3]]:item))}/>{[1,2,3].map(packIndex=><label key={packIndex}><input type="checkbox" checked={packIndex===3?true:Boolean(row[packIndex])} disabled={packIndex===3} onChange={e=>setRows(rows.map((item,i)=>i===index?[item[0],packIndex===1?e.target.checked:item[1],packIndex===2?e.target.checked:item[2],true]:item))}/><span>{packIndex===3||row[packIndex]?"Included":"Hidden"}</span></label>)}<button type="button" onClick={()=>setRows(rows.filter((_,i)=>i!==index))}>×</button></div>)}<button className="add-row-button" type="button" onClick={()=>setRows([...rows,["",false,false,true]])}>+ Add package feature</button></div>
}
function CategoryPackageFeatures({themes}:{themes:ReadyTheme[]}){
  const [categories,setCategories]=useState<string[]>([]),[category,setCategory]=useState(""),[rows,setRows]=useState<[string,boolean,boolean,boolean][]>([]),[saved,setSaved]=useState(false);
  useEffect(()=>{const next=loadThemeCategories(themes);setCategories(next);setCategory(current=>current||next[0]||"Uncategorized")},[themes]);
  useEffect(()=>setRows(loadCategoryPackageFeatures(category)),[category]);
  function save(){saveCategoryPackageFeatures(category,rows);setSaved(true);setTimeout(()=>setSaved(false),1800)}
  return <><PageTitle eyebrow="Ready theme packages" title="Category Package Features" text="Create a reusable Pack 01, Pack 02 and Pack 03 feature matrix for every theme category."><a className="admin-export" href="/admin/themes">All themes →</a></PageTitle><section className="admin-card category-package-manager"><div className="category-package-toolbar"><label><span>Theme category</span><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(item=><option key={item}>{item}</option>)}</select></label><div><b>{themes.filter(theme=>theme.category===category&&theme.packageFeatureMode!=="custom").length} connected themes</b><small>Custom themes will keep their own matrix.</small></div></div><PackageMatrix rows={rows} setRows={setRows}/><div className="category-package-save"><button onClick={save}>Save category features ↗</button>{saved&&<span>✓ Category package features saved.</span>}</div></section></>
}
function AdminTop(){return <header className="admin-topbar"><label><span>⌕</span><input placeholder="Search themes, products, orders..."/></label><div><button>♟</button><span className="admin-top-user">M</span><b>Mehedi Rahat</b></div></header>}
function PageTitle({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children:ReactNode}){return <div className="admin-page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{children}</div>}
function Card({title,children}:{title:string;children:ReactNode}){return <section className="admin-card editor-card"><h2>{title}</h2>{children}</section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="editor-field"><span>{label}</span>{children}</label>}
function fileToData(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
