"use client";
import {useEffect,useState} from "react";
import AdminSidebar from "./AdminSidebar";
import {ContactPageSettings,loadContactPageSettings,saveContactPageSettings,seedContactPageSettings} from "../contactPageStore";
export default function AdminContactPage(){
 const[data,setData]=useState<ContactPageSettings>(seedContactPageSettings),[message,setMessage]=useState("");
 useEffect(()=>setData(loadContactPageSettings()),[]);
 const set=<K extends keyof ContactPageSettings>(key:K,value:ContactPageSettings[K])=>setData(c=>({...c,[key]:value}));
 const channel=(i:number,key:string,value:string)=>set("channels",data.channels.map((x,n)=>n===i?{...x,[key]:value}:x));
 const processStep=(i:number,key:"title"|"description",value:string)=>set("processSteps",data.processSteps.map((x,n)=>n===i?{...x,[key]:value}:x));
 const save=()=>{saveContactPageSettings(data);setMessage("Contact Page saved and connected to the live website.")};
 return <main className="admin-root"><AdminSidebar active="pages"/><section className="admin-workspace"><Top/>
 <div className="admin-page-title"><div><span className="eyebrow">Website content</span><h1>Contact Page</h1><p>Manage the contact experience, communication channels and enquiry form.</p></div><a href="/contact" target="_blank">View Contact Page ↗</a></div>
 <div className="homepage-editor-layout"><div className="homepage-editor-main">
 <Card title="Hero content" visible={data.heroVisible} toggle={v=>set("heroVisible",v)}><div className="editor-grid"><Field label="Eyebrow"><input value={data.heroEyebrow} onChange={e=>set("heroEyebrow",e.target.value)}/></Field>{data.heroLines.map((x,i)=><Field label={`Headline line ${i+1}${i===2?" (highlighted)":""}`} key={i}><input value={x} onChange={e=>set("heroLines",data.heroLines.map((v,n)=>n===i?e.target.value:v))}/></Field>)}</div><Field label="Description"><textarea value={data.heroDescription} onChange={e=>set("heroDescription",e.target.value)}/></Field><div className="editor-grid">{(["primaryButtonLabel","primaryButtonLink","secondaryButtonLabel","secondaryButtonLink"] as const).map((key,i)=><Field key={key} label={["Primary button text","Primary button link","Secondary button text","Secondary button link"][i]}><input value={data[key]} onChange={e=>set(key,e.target.value)}/></Field>)}</div></Card>
 <Card title="Response card"><div className="editor-grid"><Field label="Card eyebrow"><input value={data.cardEyebrow} onChange={e=>set("cardEyebrow",e.target.value)}/></Field>{data.cardLines.map((x,i)=><Field label={`Heading line ${i+1}`} key={i}><input value={x} onChange={e=>set("cardLines",data.cardLines.map((v,n)=>n===i?e.target.value:v))}/></Field>)}<Field label="Response time"><input value={data.responseTime} onChange={e=>set("responseTime",e.target.value)}/></Field><Field label="Response label"><input value={data.responseLabel} onChange={e=>set("responseLabel",e.target.value)}/></Field></div><Field label="Trust points (one per line)"><textarea value={data.trustPoints.join("\n")} onChange={e=>set("trustPoints",lines(e.target.value))}/></Field></Card>
 <Card title="Contact details" visible={data.contactVisible} toggle={v=>set("contactVisible",v)}><div className="editor-grid"><Field label="Section eyebrow"><input value={data.contactEyebrow} onChange={e=>set("contactEyebrow",e.target.value)}/></Field><Field label="Section heading"><input value={data.contactHeading} onChange={e=>set("contactHeading",e.target.value)}/></Field></div><Field label="Section description"><textarea value={data.contactDescription} onChange={e=>set("contactDescription",e.target.value)}/></Field><div className="contact-channel-admin">{data.channels.map((x,i)=><section key={i}><b>Contact method {i+1}</b><div className="editor-grid">{(["icon","label","value","href"] as const).map((key,n)=><Field key={key} label={["Icon / letters","Label","Value","Link"][n]}><input value={x[key]} onChange={e=>channel(i,key,e.target.value)}/></Field>)}</div><Field label="Short note"><input value={x.note} onChange={e=>channel(i,"note",e.target.value)}/></Field></section>)}</div></Card>
 <Card title="Contact process" visible={data.processVisible} toggle={v=>set("processVisible",v)}><div className="editor-grid"><Field label="Section eyebrow"><input value={data.processEyebrow} onChange={e=>set("processEyebrow",e.target.value)}/></Field><Field label="Section heading"><input value={data.processHeading} onChange={e=>set("processHeading",e.target.value)}/></Field></div><div className="contact-channel-admin">{data.processSteps.map((step,i)=><section key={i}><b>Step {i+1}</b><Field label="Step title"><input value={step.title} onChange={e=>processStep(i,"title",e.target.value)}/></Field><Field label="Short description"><textarea value={step.description} onChange={e=>processStep(i,"description",e.target.value)}/></Field></section>)}</div><Field label="Bottom trust points (one per line)"><textarea value={data.processFooter.join("\n")} onChange={e=>set("processFooter",lines(e.target.value))}/></Field></Card>
 <Card title="Enquiry form content"><div className="editor-grid">{(["formEyebrow","formHeading","nameLabel","emailLabel","emailPlaceholder","mobileLabel","mobilePlaceholder","serviceLabel","detailsLabel","submitLabel","successMessage"] as const).map((key,i)=><Field key={key} label={["Form eyebrow","Form heading","Name field label","Email field label","Email placeholder","Mobile field label","Mobile placeholder","Service field label","Details field label","Submit button","Success message"][i]}><input value={data[key]} onChange={e=>set(key,e.target.value)}/></Field>)}</div><Field label="Form description"><textarea value={data.formDescription} onChange={e=>set("formDescription",e.target.value)}/></Field><Field label="Service choices (one per line)"><textarea value={data.serviceOptions.join("\n")} onChange={e=>set("serviceOptions",lines(e.target.value))}/></Field></Card>
 </div><aside className="homepage-editor-side"><section className="admin-card homepage-status-card"><span className="eyebrow">Contact page status</span><h2>Ready to update</h2><p>Saved changes appear immediately on the public Contact Page.</p><ul><li>Premium split hero</li><li>Editable buttons and links</li><li>Direct contact methods</li><li>Custom enquiry form content</li></ul></section>{message&&<p className="editor-saved">✓ {message}</p>}<button className="publish-product" onClick={save}>Save Contact Page ↗</button><button className="save-draft" onClick={()=>{setData(seedContactPageSettings);saveContactPageSettings(seedContactPageSettings);setMessage("Default Contact Page content restored.")}}>Restore default content</button></aside></div>
 </section></main>
}
const lines=(v:string)=>v.split("\n").map(x=>x.trim()).filter(Boolean);
function Top(){return <header className="admin-topbar"><label><span>⌕</span><input placeholder="Search Contact Page settings..."/></label><div><button>♟</button><span className="admin-top-user">M</span><b>Mehedi Rahat</b></div></header>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="editor-field"><span>{label}</span>{children}</label>}
function Card({title,visible,toggle,children}:{title:string;visible?:boolean;toggle?:(v:boolean)=>void;children:React.ReactNode}){return <section className="admin-card editor-card homepage-section-editor"><div className="homepage-editor-heading"><h2>{title}</h2>{toggle&&<label><input type="checkbox" checked={visible} onChange={e=>toggle(e.target.checked)}/> Show on Contact Page</label>}</div><div className="services-admin-card-body">{children}</div></section>}
