"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import AdminSidebar from "./AdminSidebar";
import {loadReviews,reviewSlug,saveReviews,StoreReview} from "../reviewStore";

export default function AdminReviews({mode}:{mode:"list"|"new"|"edit"}){
 const[reviews,setReviews]=useState<StoreReview[]>([]),[editing,setEditing]=useState<StoreReview|null>(null),[query,setQuery]=useState(""),[photo,setPhoto]=useState(""),[photoName,setPhotoName]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{const all=loadReviews();setReviews(all);if(mode==="edit"){const id=new URLSearchParams(window.location.search).get("id");const item=all.find(x=>x.id===id)||all[0]||null;setEditing(item);setPhoto(item?.photo||"");setPhotoName(item?.photoName||"")}},[mode]);
 const visible=useMemo(()=>reviews.filter(item=>`${item.name} ${item.role} ${item.quote}`.toLowerCase().includes(query.toLowerCase())),[reviews,query]);
 const persist=(next:StoreReview[])=>{const normalized=[...next].sort((a,b)=>a.order-b.order).map((x,i)=>({...x,order:i+1}));setReviews(normalized);saveReviews(normalized)};
 const move=(id:string,direction:-1|1)=>{const next=[...reviews],index=next.findIndex(x=>x.id===id),target=index+direction;if(index<0||target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];persist(next)};
 const remove=(item:StoreReview)=>{if(confirm(`Delete review from ${item.name}?`))persist(reviews.filter(x=>x.id!==item.id))};
 const upload=(file?:File)=>{if(!file)return;if(file.size>1.5*1024*1024){setMessage("Image must be smaller than 1.5 MB.");return}const reader=new FileReader();reader.onload=()=>{setPhoto(String(reader.result));setPhotoName(file.name)};reader.readAsDataURL(file)};
 const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget),name=String(data.get("name")||"");const item:StoreReview={id:editing?.id||reviewSlug(name),name,role:String(data.get("role")||""),company:String(data.get("company")||""),quote:String(data.get("quote")||""),rating:Number(data.get("rating")||5),status:String(data.get("status")) as StoreReview["status"],order:editing?.order||reviews.length+1,photo,photoName};persist(mode==="edit"?reviews.map(x=>x.id===editing?.id?item:x):[...reviews,item]);setEditing(item);setMessage("Review saved and connected to the Homepage.")};
 return <main className="admin-root"><AdminSidebar active="reviews"/><section className="admin-workspace"><AdminTop/>
 {mode==="list"?<><div className="admin-page-title"><div><span className="eyebrow">Customer trust</span><h1>Reviews / Testimonials</h1><p>Manage client feedback shown on your Homepage.</p></div><a href="/admin/reviews/new">Add new review +</a></div><section className="product-admin-stats">{[["All reviews",reviews.length],["Published",reviews.filter(x=>x.status==="Published").length],["Draft",reviews.filter(x=>x.status==="Draft").length],["Average rating",reviews.length?(reviews.reduce((s,x)=>s+x.rating,0)/reviews.length).toFixed(1):"0.0"]].map(item=><article key={String(item[0])}><span>{item[0]}</span><strong>{item[1]}</strong></article>)}</section><section className="admin-card review-admin-card"><div className="product-toolbar"><label>⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reviews..."/></label></div><div className="review-admin-grid">{visible.map(item=><article key={item.id}>{item.photo?<img src={item.photo} alt=""/>:<i>{item.name.charAt(0)}</i>}<div><span>{"★".repeat(item.rating)}</span><h2>{item.name}</h2><small>{item.role}{item.company?` · ${item.company}`:""}</small><p>{item.quote}</p><footer><em className={item.status.toLowerCase()}>{item.status}</em><div className="service-order-actions"><button onClick={()=>move(item.id,-1)}>↑</button><button onClick={()=>move(item.id,1)}>↓</button></div><a href={`/admin/reviews/edit?id=${item.id}`}>Edit</a><button onClick={()=>remove(item)}>×</button></footer></div></article>)}</div></section></>:
 <><div className="admin-page-title"><div><span className="eyebrow">Reviews / Testimonials</span><h1>{mode==="new"?"Add Review":"Edit Review"}</h1><p>Configure client identity, rating, feedback and visibility.</p></div><a className="admin-export" href="/admin/reviews">Back to reviews →</a></div><form className="product-editor" onSubmit={submit}><div className="product-editor-main"><section className="admin-card editor-card"><h2>Client feedback</h2><div className="editor-grid"><Field label="Client name"><input name="name" required defaultValue={editing?.name}/></Field><Field label="Role"><input name="role" required defaultValue={editing?.role}/></Field><Field label="Company (optional)"><input name="company" defaultValue={editing?.company}/></Field><Field label="Rating"><select name="rating" defaultValue={editing?.rating||5}><option value="5">5 Stars</option><option value="4">4 Stars</option><option value="3">3 Stars</option><option value="2">2 Stars</option><option value="1">1 Star</option></select></Field><Field label="Publish status"><select name="status" defaultValue={editing?.status||"Published"}><option>Published</option><option>Draft</option></select></Field></div><Field label="Review / testimonial"><textarea name="quote" required defaultValue={editing?.quote}/></Field></section></div><aside className="product-editor-side"><section className="admin-card editor-card"><h2>Client photo</h2><label className="image-upload-placeholder">{photo?<img src={photo} alt="Preview"/>:<><i>◇</i><b>Upload client image</b><small>PNG, JPG or WebP · max 1.5 MB</small></>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0])}/><span>{photoName||"Choose image"}</span></label></section>{message&&<p className="editor-saved">✓ {message}</p>}<button className="publish-product" type="submit">{mode==="new"?"Save & Publish Review":"Update Review"} ↗</button><a className="save-draft service-cancel" href="/admin/reviews">Cancel</a></aside></form></>}</section></main>
}
function AdminTop(){return <header className="admin-topbar"><label><span>⌕</span><input placeholder="Search reviews, clients..."/></label><div><button>♟</button><span className="admin-top-user">M</span><b>Mehedi Rahat</b></div></header>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="editor-field"><span>{label}</span>{children}</label>}
