"use client";
import {useEffect,useState} from "react";
import AdminSidebar from "./AdminSidebar";
import {MrCommercePageSettings,loadMrCommercePageSettings,saveMrCommercePageSettings,seedMrCommercePageSettings} from "../mrCommercePageStore";
const lines=(v:string)=>v.split("\n").map(x=>x.trim()).filter(Boolean);
export default function AdminMrCommercePage(){
 const[data,setData]=useState(seedMrCommercePageSettings),[message,setMessage]=useState("");
 useEffect(()=>setData(loadMrCommercePageSettings()),[]);
 const set=(key:keyof MrCommercePageSettings,value:any)=>setData(c=>({...c,[key]:value}));
 const item=(key:keyof MrCommercePageSettings,index:number,field:string,value:any)=>setData(c=>({...c,[key]:(c[key] as any[]).map((x,i)=>i===index?{...x,[field]:value}:x)}));
 const save=()=>{saveMrCommercePageSettings(data);setMessage("MR Commerce Pro Page saved and connected to the live page.")};
 return <main className="admin-root"><AdminSidebar active="pages"/><section className="admin-workspace"><Top/>
  <div className="admin-page-title"><div><span className="eyebrow">MR Exclusive content</span><h1>MR Commerce Pro Page</h1><p>Edit the complete landing page from one place.</p></div><a href="/mr-commerce-pro" target="_blank">View live page ↗</a></div>
  <div className="homepage-editor-layout"><div className="homepage-editor-main">
   <Card title="Hero and video">
    <Grid><Field label="Eyebrow"><input value={data.heroEyebrow} onChange={e=>set("heroEyebrow",e.target.value)}/></Field><Field label="Headline"><input value={data.heroTitle} onChange={e=>set("heroTitle",e.target.value)}/></Field><Field label="Highlighted headline"><input value={data.heroHighlight} onChange={e=>set("heroHighlight",e.target.value)}/></Field><Field label="Video URL"><input value={data.videoUrl} onChange={e=>set("videoUrl",e.target.value)} placeholder="YouTube or video URL"/></Field></Grid>
    <Field label="Hero description"><textarea value={data.heroDescription} onChange={e=>set("heroDescription",e.target.value)}/></Field>
    <Grid><Field label="Primary button label"><input value={data.primaryLabel} onChange={e=>set("primaryLabel",e.target.value)}/></Field><Field label="Primary button URL"><input value={data.primaryUrl} onChange={e=>set("primaryUrl",e.target.value)}/></Field><Field label="Secondary button label"><input value={data.secondaryLabel} onChange={e=>set("secondaryLabel",e.target.value)}/></Field><Field label="Secondary button URL"><input value={data.secondaryUrl} onChange={e=>set("secondaryUrl",e.target.value)}/></Field><Field label="Video eyebrow"><input value={data.videoEyebrow} onChange={e=>set("videoEyebrow",e.target.value)}/></Field><Field label="Video title"><input value={data.videoTitle} onChange={e=>set("videoTitle",e.target.value)}/></Field></Grid>
    <Field label="Video description"><input value={data.videoDescription} onChange={e=>set("videoDescription",e.target.value)}/></Field>
    <Repeat>{data.stats.map((x,i)=><div key={i}><b>Statistic {i+1}</b><input value={x.value} onChange={e=>item("stats",i,"value",e.target.value)}/><input value={x.label} onChange={e=>item("stats",i,"label",e.target.value)}/></div>)}</Repeat>
   </Card>
   <Card title="Overview section"><Heading data={data} set={set} prefix="overview"/><Field label="Description"><textarea value={data.overviewDescription} onChange={e=>set("overviewDescription",e.target.value)}/></Field><Repeat>{data.overviewCards.map((x,i)=><div key={i}><b>Card {i+1}</b><input value={x.number} onChange={e=>item("overviewCards",i,"number",e.target.value)}/><input value={x.title} onChange={e=>item("overviewCards",i,"title",e.target.value)}/><textarea value={x.description} onChange={e=>item("overviewCards",i,"description",e.target.value)}/></div>)}</Repeat></Card>
   <Card title="Core feature stories"><Heading data={data} set={set} prefix="features"/><div className="mrc-admin-features">{data.featureGroups.map((x,i)=><div key={i}><b>Feature story {i+1}</b><Grid><Field label="Number"><input value={x.number} onChange={e=>item("featureGroups",i,"number",e.target.value)}/></Field><Field label="Label"><input value={x.label} onChange={e=>item("featureGroups",i,"label",e.target.value)}/></Field><Field label="Title"><input value={x.title} onChange={e=>item("featureGroups",i,"title",e.target.value)}/></Field><Field label="Screenshot URL"><input value={x.image} onChange={e=>item("featureGroups",i,"image",e.target.value)}/></Field></Grid><Field label="Description"><textarea value={x.text} onChange={e=>item("featureGroups",i,"text",e.target.value)}/></Field><Field label="Feature tabs (one per line)"><textarea value={x.points.join("\n")} onChange={e=>item("featureGroups",i,"points",lines(e.target.value))}/></Field></div>)}</div></Card>
   <Card title="More inside the plugin"><Heading data={data} set={set} prefix="capabilities"/><Repeat>{data.capabilityGroups.map((x,i)=><div key={i}><b>Group {i+1}</b><input value={x.title} onChange={e=>item("capabilityGroups",i,"title",e.target.value)}/><textarea value={x.items.join("\n")} onChange={e=>item("capabilityGroups",i,"items",lines(e.target.value))}/></div>)}</Repeat></Card>
   <Card title="Workflow section"><Heading data={data} set={set} prefix="workflow"/><Repeat>{data.workflowSteps.map((x,i)=><div key={i}><b>Step {i+1}</b><input value={x.number} onChange={e=>item("workflowSteps",i,"number",e.target.value)}/><input value={x.title} onChange={e=>item("workflowSteps",i,"title",e.target.value)}/><textarea value={x.description} onChange={e=>item("workflowSteps",i,"description",e.target.value)}/></div>)}</Repeat></Card>
   <Card title="Free and Pro plans"><Heading data={data} set={set} prefix="pricing"/><div className="mrc-admin-plans">
    <div><h3>Free plan</h3><Grid><Field label="Title"><input value={data.freeTitle} onChange={e=>set("freeTitle",e.target.value)}/></Field><Field label="Price"><input value={data.freePrice} onChange={e=>set("freePrice",e.target.value)}/></Field><Field label="Price note"><input value={data.freePriceNote} onChange={e=>set("freePriceNote",e.target.value)}/></Field><Field label="Download URL"><input value={data.freeDownloadUrl} onChange={e=>set("freeDownloadUrl",e.target.value)}/></Field></Grid><Field label="Description"><textarea value={data.freeDescription} onChange={e=>set("freeDescription",e.target.value)}/></Field><Field label="Features (one per line)"><textarea value={data.freeFeatures.join("\n")} onChange={e=>set("freeFeatures",lines(e.target.value))}/></Field><Grid><Field label="Value title"><input value={data.freeValueTitle} onChange={e=>set("freeValueTitle",e.target.value)}/></Field><Field label="Button label"><input value={data.freeButtonLabel} onChange={e=>set("freeButtonLabel",e.target.value)}/></Field></Grid><Field label="Value description"><input value={data.freeValueDescription} onChange={e=>set("freeValueDescription",e.target.value)}/></Field><Field label="Benefits (one per line)"><textarea value={data.freeBenefits.join("\n")} onChange={e=>set("freeBenefits",lines(e.target.value))}/></Field></div>
    <div><h3>Pro plan</h3><Grid><Field label="Title"><input value={data.proTitle} onChange={e=>set("proTitle",e.target.value)}/></Field><Field label="Sale price"><input type="number" value={data.proPrice} onChange={e=>set("proPrice",Number(e.target.value))}/></Field><Field label="Regular price"><input value={data.proRegularPrice} onChange={e=>set("proRegularPrice",e.target.value)}/></Field><Field label="Button label"><input value={data.proButtonLabel} onChange={e=>set("proButtonLabel",e.target.value)}/></Field><Field label="Offer badge"><input value={data.launchBadge} onChange={e=>set("launchBadge",e.target.value)}/></Field><Field label="Launch limit"><input type="number" value={data.launchLimit} onChange={e=>set("launchLimit",Number(e.target.value))}/></Field></Grid><Field label="Description"><textarea value={data.proDescription} onChange={e=>set("proDescription",e.target.value)}/></Field><Field label="Features (one per line)"><textarea value={data.proFeatures.join("\n")} onChange={e=>set("proFeatures",lines(e.target.value))}/></Field></div>
   </div></Card>
  </div><aside className="homepage-editor-side"><section className="admin-card homepage-status-card"><span className="eyebrow">MR Commerce Page</span><h2>Ready to update</h2><p>Saved changes appear on the landing page immediately.</p><ul><li>Hero and video</li><li>Features and screenshots</li><li>Workflow and capabilities</li><li>Free and Pro pricing</li></ul></section>{message&&<p className="editor-saved">✓ {message}</p>}<button className="publish-product" onClick={save}>Save MR Commerce Page ↗</button><button className="save-draft" onClick={()=>{setData(seedMrCommercePageSettings);saveMrCommercePageSettings(seedMrCommercePageSettings);setMessage("Default content restored.")}}>Restore default content</button></aside></div>
 </section></main>
}
function Top(){return <header className="admin-topbar"><label><span>⌕</span><input placeholder="Search MR Commerce Page settings..."/></label><div><button>♟</button><span className="admin-top-user">M</span><b>Mehedi Rahat</b></div></header>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="admin-card editor-card homepage-section-editor"><div className="homepage-editor-heading"><h2>{title}</h2></div><div className="services-admin-card-body">{children}</div></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="editor-field"><span>{label}</span>{children}</label>}
function Grid({children}:{children:React.ReactNode}){return <div className="editor-grid">{children}</div>}
function Repeat({children}:{children:React.ReactNode}){return <div className="services-admin-repeat">{children}</div>}
function Heading({data,set,prefix}:{data:any;set:(key:any,value:any)=>void;prefix:string}){return <Grid><Field label="Eyebrow"><input value={data[`${prefix}Eyebrow`]} onChange={e=>set(`${prefix}Eyebrow`,e.target.value)}/></Field><Field label="Heading"><input value={data[`${prefix}Title`]} onChange={e=>set(`${prefix}Title`,e.target.value)}/></Field><Field label="Highlighted heading"><input value={data[`${prefix}Highlight`]} onChange={e=>set(`${prefix}Highlight`,e.target.value)}/></Field></Grid>}
