"use client";

import { useEffect, useState } from "react";
import AdminSidebar from "./AdminSidebar";
import { updateStoredOrderStatus } from "../orderStore";

type Order={number:string;status:string;payment:string;total:number;customer?:{name:string;email:string;phone:string};items?:{name:string;variation:string;price:number;quantity:number}[];senderNumber?:string;transactionId?:string};

const adminMenu=[["▦","Overview","/admin"],["▣","Orders","/admin/orders"],["♙","Customers","#customers"],["◇","Products","/admin/products"],["♛","Membership","#membership"],["▰","Support Tickets","#tickets"],["⚙","Activations","#activations"],["⌁","Licenses","#licenses"],["▤","Reports","#reports"],["⚙","Settings","#settings"]];

export default function AdminPortal({page}:{page:"overview"|"orders"}) {
  const [order,setOrder]=useState<Order|null>(null),[filter,setFilter]=useState("All"),[notice,setNotice]=useState("");
  useEffect(()=>setOrder(JSON.parse(localStorage.getItem("mr-last-order")||"null")),[]);
  function updateStatus(status:string){if(!order)return;const updated={...order,status};updateStoredOrderStatus(order.number,status);setOrder(updated);setNotice(`Order ${order.number} changed to ${status}.`)}
  const pending=order?.status==="Payment Verification"?1:0,completed=order?.status==="Completed"?1:0,total=order?.total||0;
  return <main className="admin-root"><AdminSidebar active={page}/><aside className="legacy-admin-sidebar"><a className="admin-brand" href="/admin"><span>MR</span><div><b>MEHEDI RAHAT</b><small>ADMIN PANEL</small></div></a><div className="admin-owner"><span>M</span><div><b>Mehedi Rahat</b><small>Super Admin</small></div></div><nav>{adminMenu.map(([icon,label,url],i)=><a className={(page==="overview"&&i===0)||(page==="orders"&&i===1)?"active":""} href={url} key={label}><i>{icon}</i><span>{label}</span>{label==="Orders"&&<b>{pending}</b>}</a>)}</nav><div className="admin-sidebar-foot"><a href="/">View website ↗</a><button>Sign out</button></div></aside>
    <section className="admin-workspace"><header className="admin-topbar"><label><span>⌕</span><input placeholder="Search orders, customers, products..." /></label><div><button>♟</button><span className="admin-top-user">M</span><b>Mehedi Rahat</b></div></header>
      {page==="overview"?<><div className="admin-page-title"><div><span className="eyebrow">Business overview</span><h1>Good morning, Mehedi.</h1><p>Here is what is happening with your business today.</p></div><a href="/admin/orders">Review pending orders ↗</a></div>
      <section className="admin-kpis">{[["৳",`৳ ${total.toLocaleString("en-US")}`,"Total Revenue","From completed orders"],["▣",order?1:0,"Total Orders",`${pending} awaiting verification`],["♙",order?1:0,"Customers","Active customer records"],["◉",pending,"Pending Payments","Needs your review"],["▰",0,"Open Tickets","No urgent tickets"]].map(([icon,value,label,note],i)=><article key={String(label)}><i className={`kpi-${i}`}>{icon}</i><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article>)}</section>
      <section className="admin-overview-grid"><div className="admin-card revenue-card"><div className="admin-card-head"><div><span className="eyebrow">Revenue</span><h2>Sales performance</h2></div><select><option>Last 7 days</option><option>Last 30 days</option></select></div><div className="admin-chart"><div style={{height:"24%"}}/><div style={{height:"40%"}}/><div style={{height:"32%"}}/><div style={{height:"58%"}}/><div style={{height:"47%"}}/><div style={{height:"72%"}}/><div style={{height:"64%"}}/></div><div className="chart-labels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div><div className="admin-card attention-card"><div className="admin-card-head"><div><span className="eyebrow">Needs attention</span><h2>Action queue</h2></div></div>{[["Payment verification",pending],["Support tickets",0],["Activation requests",0],["Low stock products",0]].map(([x,n])=><a href={x==="Payment verification"?"/admin/orders":"#"} key={String(x)}><span>{x}</span><b>{n}</b><i>→</i></a>)}</div></section>
      <section className="admin-card admin-recent"><div className="admin-card-head"><div><span className="eyebrow">Latest activity</span><h2>Recent orders</h2></div><a href="/admin/orders">View all orders →</a></div><OrderTable order={order}/></section></>:
      <><div className="admin-page-title"><div><span className="eyebrow">Order management</span><h1>Orders</h1><p>Review payments, update status and manage customer orders.</p></div><a className="admin-export" href="#export">Export orders ↓</a></div>
      <section className="admin-kpis order-kpis">{[["▣",order?1:0,"All orders"],["◉",pending,"Payment Verification"],["✓",completed,"Completed"],["×",order?.status==="Rejected"?1:0,"Rejected"]].map(([ic,val,label],i)=><article key={String(label)}><i className={`kpi-${i}`}>{ic}</i><div><span>{label}</span><strong>{val}</strong></div></article>)}</section>
      <section className="admin-card admin-orders-card"><div className="order-toolbar"><div>{["All","Payment Verification","Completed","Rejected"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><label>⌕ <input placeholder="Search by order or customer..." /></label></div>{notice&&<p className="admin-notice">✓ {notice}</p>}<OrderTable order={filter==="All"||order?.status===filter?order:null} actions onUpdate={updateStatus}/></section>
      {order&&<section className="admin-order-detail"><div className="admin-card order-customer"><div className="admin-card-head"><h2>Customer &amp; payment</h2><span className={`admin-status ${order.status.toLowerCase().replaceAll(" ","-")}`}>{order.status}</span></div><dl><div><dt>Customer</dt><dd>{order.customer?.name||"Demo Customer"}</dd></div><div><dt>Email</dt><dd>{order.customer?.email||"demo@mehedirahat.com"}</dd></div><div><dt>Phone</dt><dd>{order.customer?.phone||"—"}</dd></div><div><dt>Payment</dt><dd>{order.payment}</dd></div><div><dt>Sender number</dt><dd>{order.senderNumber||"Submitted at checkout"}</dd></div><div><dt>Transaction ID</dt><dd>{order.transactionId||"Reference submitted"}</dd></div></dl></div><div className="admin-card order-review"><span className="eyebrow">Verification action</span><h2>Review this payment</h2><p>Confirm the received amount and transaction reference before approving the order.</p><div><button onClick={()=>updateStatus("Completed")}>Approve &amp; Complete</button><button onClick={()=>updateStatus("On Hold")}>Put on Hold</button><button onClick={()=>updateStatus("Rejected")}>Reject</button></div><small>Customer dashboard status updates immediately in this local prototype.</small></div></section>}</>}
    </section></main>
}
function OrderTable({order,actions,onUpdate}:{order:Order|null;actions?:boolean;onUpdate?:(x:string)=>void}){return order?<div className="admin-order-table"><div className="admin-table-head"><span>Order</span><span>Customer</span><span>Payment</span><span>Total</span><span>Status</span><span>Action</span></div><div className="admin-table-row"><b>{order.number}</b><span>{order.customer?.name||"Demo Customer"}</span><span>{order.payment}</span><strong>৳ {order.total.toLocaleString("en-US")}</strong><em className={`admin-status ${order.status.toLowerCase().replaceAll(" ","-")}`}>{order.status}</em>{actions?<select value={order.status} onChange={e=>onUpdate?.(e.target.value)}><option>Payment Verification</option><option>On Hold</option><option>Completed</option><option>Rejected</option></select>:<a href="/admin/orders">Review →</a>}</div></div>:<div className="admin-empty"><i>▣</i><b>No orders found</b><p>New customer orders will appear here.</p></div>}
