"use client";

import { useEffect, useState } from "react";
import AdminSidebar from "./AdminSidebar";
import styles from "./AdminCustomerDetail.module.css";

type Customer = { id: string; name: string; email: string; phone: string; createdAt: string; lifetimeSpend: number; hasAccount: boolean };
type Order = { id: string; number: string; status: string; total: number; payment: string; createdAt: string; transactionId?: string; productNames?: string; activeDomains: number };
type License = { id: string; licenseId?: string; status: string; activationLimit: number; productName: string; variation: string; activations: { id: string; domain: string; status: string; activatedAt?: string }[] };
type Membership = { current: { name: string; discountPercent: number }; next: { name: string } | null; remaining: number; level: string; discount: string; nextLabel: string };
type Detail = { customer: Customer; membership: Membership; orders: Order[]; licenses: License[]; summary: { totalOrders: number; completedOrders: number; refundedOrders: number; completedValue: number; activeDomains: number } };
const labels: Record<string, string> = { payment_verification: "Payment verification", on_hold: "On hold", completed: "Completed", rejected: "Rejected", refunded: "Refunded" };
const date = (value: string) => new Intl.DateTimeFormat("en-BD", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
export default function AdminCustomerDetail({ id }: { id: string }) {
  const [data, setData] = useState<Detail | null>(null), [error, setError] = useState("");
  useEffect(() => { void fetch(`/api/admin/customers/${encodeURIComponent(id)}`, { cache: "no-store" }).then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.error || "Customer could not be loaded."); setData(result); }).catch(reason => setError(reason instanceof Error ? reason.message : "Customer could not be loaded.")); }, [id]);
  const membership = data?.membership || null;
  return <main className="admin-root"><AdminSidebar active="customers"/><section className="admin-workspace">
    <header className="admin-topbar"><label><span>⌕</span><input placeholder="Search customers, orders or licenses..."/></label><div><span className="admin-top-user">M</span><b>Mehedi Rahat</b></div></header>
    {!data ? <section className="admin-card customer-detail-state"><b>{error || "Loading customer profile…"}</b>{error && <a href="/admin/customers">← Back to customers</a>}</section> : <><div className="admin-page-title customer-detail-title"><div><span className="eyebrow">CUSTOMER PROFILE</span><h1>{data.customer.name}</h1><p>{data.customer.email} · {data.customer.phone}</p></div><a className="admin-outline-button" href="/admin/customers">← All customers</a></div>
      <section className={`${styles.profileStrip} customer-profile-strip`}><span className={`${styles.avatar} customer-profile-avatar`}>{data.customer.name.charAt(0).toUpperCase()}</span><div className={styles.profileCopy}><span className="eyebrow">CUSTOMER STATUS</span><h2>{data.customer.hasAccount ? "Registered customer" : "Order customer"}</h2><p>Joined {date(data.customer.createdAt)}</p></div><a className={styles.emailAction} href={`mailto:${data.customer.email}`}>Email customer ↗</a></section>
      <section className="admin-kpis customer-detail-kpis"><article><i>▣</i><div><span>Total orders</span><strong>{data.summary.totalOrders}</strong></div></article><article><i className="kpi-1">✓</i><div><span>Completed orders</span><strong>{data.summary.completedOrders}</strong></div></article><article><i className="kpi-2">৳</i><div><span>Lifetime spend</span><strong>৳ {data.customer.lifetimeSpend.toLocaleString("en-US")}</strong></div></article><article><i className="kpi-3">◎</i><div><span>Active domains</span><strong>{data.summary.activeDomains}</strong></div></article><article className={`membership-kpi ${membership?.level.toLowerCase()}`}><i>♛</i><div><span>Membership status</span><strong>{membership?.level}</strong><small>{membership?.discount} · {membership?.nextLabel}</small></div></article></section>
      <section className={`${styles.contentGrid} customer-detail-grid`}><article className={`${styles.card} customer-orders-card`}><header className={styles.cardHeader}><div><span className="eyebrow">PURCHASE HISTORY</span><h2>All orders</h2></div><span>{data.orders.length} total</span></header><div className={`${styles.orderList} customer-order-list`}>{data.orders.length ? data.orders.map(order => <article key={order.id}><div><b>{order.number}</b><small>{order.productNames || "No product details"}</small><small>{date(order.createdAt)} · {order.payment.toUpperCase()}</small></div><em className={`admin-status ${order.status}`}>{labels[order.status] || order.status}</em><strong>৳ {order.total.toLocaleString("en-US")}</strong><a href={`/admin/orders?order=${encodeURIComponent(order.id)}`}>Review →</a></article>) : <p>No orders yet.</p>}</div></article>
        <aside className={`${styles.card} ${styles.accountCard} customer-account-card`}><span className="eyebrow">ACCOUNT INFORMATION</span><h2>Contact details</h2><dl><div><dt>Email</dt><dd>{data.customer.email}</dd></div><div><dt>Phone</dt><dd>{data.customer.phone}</dd></div><div><dt>Account access</dt><dd>{data.customer.hasAccount ? "Registered account" : "No account yet"}</dd></div><div><dt>Refunded orders</dt><dd>{data.summary.refundedOrders}</dd></div></dl></aside></section>
      <section className={`${styles.card} ${styles.licensesCard} customer-licenses-card`}><header className={styles.cardHeader}><div><span className="eyebrow">DIGITAL ACCESS</span><h2>Licenses & activated domains</h2></div><span>{data.licenses.length} license{data.licenses.length === 1 ? "" : "s"}</span></header>{data.licenses.length ? <div className={`${styles.licenseGrid} customer-license-grid`}>{data.licenses.map(license => <article key={license.id}><div><b>{license.productName}</b><small>{license.variation}</small></div><em className={`customer-license-status ${license.status}`}>{license.status}</em><strong>{license.licenseId || "License pending"}</strong><p>{license.activations.filter(item => item.status === "active").length} of {license.activationLimit} domains active</p><div className="customer-domain-chips">{license.activations.length ? license.activations.map(item => <span key={item.id} className={item.status}>{item.domain}</span>) : <small>No domains activated.</small>}</div></article>)}</div> : <p className="customers-state">No license entitlements have been created yet.</p>}</section>
    </>}</section></main>;
}
