"use client";

import { FormEvent, useEffect, useState } from "react";
import SiteFooter from "../SiteFooter";
import CustomerSidebar from "./CustomerSidebar";

type Customer = { name: string; email: string; phone: string };
const request = async (method: string, body?: unknown) => { const response = await fetch("/api/customer/account", { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }), data = await response.json(); return { response, data }; };

export default function AccountDetails() {
  const [customer, setCustomer] = useState<Customer | null>(null), [notice, setNotice] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  useEffect(() => { request("GET").then(({ response, data }) => response.ok ? setCustomer(data.customer) : window.location.assign("/login")); }, []);
  async function profile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(""); const { response, data } = await request("PATCH", { name: form.get("name"), phone: form.get("phone") }); setBusy(false); if (!response.ok) return setError(data.error); setCustomer(data.customer); setNotice("Profile updated."); }
  async function email(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(""); const { response, data } = await request("PUT", { email: form.get("email"), currentPassword: form.get("currentPassword") }); setBusy(false); if (!response.ok) return setError(data.error); setCustomer(data.customer); event.currentTarget.reset(); setNotice(data.message); }
  async function password(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget), next = String(form.get("password") || ""); if (next !== String(form.get("confirmPassword") || "")) return setError("New passwords do not match."); setBusy(true); setError(""); const { response, data } = await request("POST", { currentPassword: form.get("currentPassword"), password: next }); setBusy(false); if (!response.ok) return setError(data.error); event.currentTarget.reset(); setNotice(data.message); }
  if (!customer) return <main className="account-loading">Loading your account…</main>;
  return <main><section className="portal-page"><div className="portal-shell"><CustomerSidebar active="/account/account-details" /><div className="portal-main"><div className="portal-top"><label><input placeholder="Search your account..." /><span>⌕</span></label><div className="portal-user"><span>{customer.name.charAt(0)}</span><b>{customer.name}</b></div></div><header className="portal-section-head"><div className="section-head-icon">♙</div><div><span className="eyebrow">Customer account</span><h1>Account Details</h1><p>Manage your profile, email address and password securely.</p></div><a href="/account">Back to dashboard →</a></header>{error && <p className="activation-message error">{error}</p>}{notice && <p className="activation-message success">✓ {notice}</p>}<section className="account-settings-layout"><form className="portal-content-card settings-form" onSubmit={profile}><div className="portal-heading"><h2>Personal information</h2><span>Profile</span></div><div className="settings-grid"><label><span>Full name</span><input name="name" defaultValue={customer.name} required /></label><label><span>Phone number</span><input name="phone" defaultValue={customer.phone} required /></label></div><button disabled={busy}>Save profile →</button></form><form className="portal-content-card settings-form" onSubmit={email}><div className="portal-heading"><h2>Change email address</h2><span>Protected</span></div><label><span>New email address</span><input name="email" type="email" defaultValue={customer.email} required /></label><label><span>Current password</span><input name="currentPassword" type="password" autoComplete="current-password" required /></label><button disabled={busy}>Update email →</button></form><form className="portal-content-card settings-form" onSubmit={password}><div className="portal-heading"><h2>Change password</h2><span>Protected</span></div><div className="settings-grid"><label><span>Current password</span><input name="currentPassword" type="password" autoComplete="current-password" required /></label><label><span>New password</span><input name="password" type="password" minLength={8} autoComplete="new-password" required /></label><label className="wide-setting"><span>Confirm new password</span><input name="confirmPassword" type="password" minLength={8} autoComplete="new-password" required /></label></div><button disabled={busy}>Change password →</button></form></section></div></div></section><SiteFooter /></main>;
}
