"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import SiteFooter from "../SiteFooter";
import CustomerSidebar from "./CustomerSidebar";
type User = { name: string }; type Address = { id: string; label: string; recipientName: string; phone: string; line1: string; line2: string; city: string; postcode: string; country: string; isDefault: boolean };

export default function Addresses() { const [user, setUser] = useState<User | null>(null), [addresses, setAddresses] = useState<Address[]>([]), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false); const load = useCallback(async () => { const [session, list] = await Promise.all([fetch("/api/customer/session", { cache: "no-store" }), fetch("/api/customer/addresses", { cache: "no-store" })]); const first = await session.json(), second = await list.json(); if (!session.ok || !list.ok) return window.location.assign("/login"); setUser(first.customer); setAddresses(second.addresses || []); }, []); useEffect(() => { void load(); }, [load]); async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(""); const response = await fetch("/api/customer/addresses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }), data = await response.json(); setBusy(false); if (!response.ok) return setError(data.error); event.currentTarget.reset(); setNotice(data.message); await load(); } async function remove(id: string) { await fetch(`/api/customer/addresses?id=${encodeURIComponent(id)}`, { method: "DELETE" }); await load(); }
if (!user) return <main className="account-loading">Loading your account…</main>; return <main><section className="portal-page"><div className="portal-shell"><CustomerSidebar active="/account/addresses" /><div className="portal-main"><div className="portal-top"><label><input placeholder="Search your account..." /><span>⌕</span></label><div className="portal-user"><span>{user.name.charAt(0)}</span><b>{user.name}</b></div></div><header className="portal-section-head"><div className="section-head-icon">◆</div><div><span className="eyebrow">Customer account</span><h1>Addresses</h1><p>Save service and contact addresses for your account.</p></div><a href="/account">Back to dashboard →</a></header><section className="account-settings-layout"><form className="portal-content-card settings-form" onSubmit={save}><div className="portal-heading"><h2>Add an address</h2><span>Optional</span></div><div className="settings-grid"><label><span>Address label</span><input name="label" placeholder="Home / Office" /></label><label><span>Recipient name</span><input name="recipientName" required /></label><label><span>Contact phone</span><input name="phone" required /></label><label className="wide-setting"><span>Street address</span><input name="line1" required /></label><label className="wide-setting"><span>Address line 2</span><input name="line2" /></label><label><span>City / Area</span><input name="city" required /></label><label><span>Postcode</span><input name="postcode" /></label><label><span>Country</span><input name="country" defaultValue="Bangladesh" /></label><label><span><input name="isDefault" type="checkbox" /> Set as default address</span></label></div>{error && <p className="activation-message error">{error}</p>}{notice && <p className="activation-message success">✓ {notice}</p>}<button disabled={busy}>{busy ? "Saving…" : "Save address →"}</button></form><section className="portal-content-card activation-history"><div className="portal-heading"><h2>Saved addresses</h2><span>{addresses.length} saved</span></div>{addresses.length ? <div className="address-list">{addresses.map(address => <article key={address.id}><div><b>{address.label}{address.isDefault ? " · Default" : ""}</b><small>{address.recipientName} · {address.phone}</small><p>{address.line1}{address.line2 ? `, ${address.line2}` : ""}, {address.city}{address.postcode ? ` ${address.postcode}` : ""}, {address.country}</p></div><button onClick={() => void remove(address.id)}>Remove</button></article>)}</div> : <div className="section-empty"><i>◆</i><h3>No saved addresses</h3><p>Add a service address when you need one.</p></div>}</section></section></div></div></section><SiteFooter /></main>; }
