"use client";

import { FormEvent, useEffect, useState } from "react";
import SiteFooter from "../SiteFooter";

type Kind = "orders"|"downloads"|"membership"|"support-tickets"|"activation-requests"|"wishlist"|"account-details"|"addresses"|"payment-methods";
type User = { name:string; email:string; phone?:string; lifetimeSpend?:number };
type Membership = { level:string; current:{discountPercent:number}; next:{name:string;discountPercent:number}|null; remaining:number; tiers:{name:string;minimumSpend:number;discountPercent:number}[] };
type Order = { number:string; status:string; payment:string; total:number; items?:{name:string;variation:string}[] };
const menu:[string,string,string][]=[["⌂","Dashboard","/account"],["▣","Orders","/account/orders"],["↓","Downloads","/account/downloads"],["♛","Membership","/account/membership"],["▰","Support Tickets","/account/support-tickets"],["⚙","Activation Requests","/account/activation-requests"],["♡","Wishlist","/account/wishlist"]];
const titles:Record<Kind,[string,string,string]>={orders:["My Orders","View purchases, payment status and order details.","▣"],downloads:["Downloads","Access purchased products and available files.","↓"],membership:["Membership Rewards","Track spending, levels and purchase discounts.","♛"],"support-tickets":["Support Tickets","Get direct help with your orders and products.","▰"],"activation-requests":["Activation Requests","Submit and track plugin or theme activation support.","⚙"],wishlist:["My Wishlist","Keep products you want to purchase later.","♡"],"account-details":["Account Details","Keep your personal information accurate and up to date.","♙"],addresses:["Addresses","Manage your contact and service address.","◆"],"payment-methods":["Payment Methods","Choose your preferred payment option for faster checkout.","▣"]};

export default function PortalSection({kind}:{kind:Kind}) {
  const [user,setUser]=useState<User|null>(null),[order,setOrder]=useState<Order|null>(null),[membership,setMembership]=useState<Membership|null>(null),[saved,setSaved]=useState(false);
  useEffect(()=>{fetch("/api/customer/session",{cache:"no-store"}).then(async response=>{const result=await response.json();if(!response.ok)return void window.location.assign("/login");setUser(result.customer);setMembership(result.membership);setOrder(result.latestOrder);}).catch(()=>window.location.assign("/login"));},[]);
  if(!user)return <main className="account-loading">Loading your account…</main>;
  const [title,description,icon]=titles[kind], spent=Number(user.lifetimeSpend||0), remaining=membership?.remaining||0;
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaved(true);e.currentTarget.reset();}
  return <main><section className="portal-page"><div className="portal-shell">
    <aside className="portal-sidebar portal-inner-sidebar"><a className="portal-logo" href="/"><span className="brand-mark">MR</span><span><b>MEHEDI RAHAT</b><small>Digital Growth Partner</small></span></a><nav>{menu.map(([ic,label,url])=><a className={kind===url.split("/").pop()?"active":""} href={url} key={label}><i>{ic}</i><span>{label}</span>{["Orders","Downloads","Support Tickets","Activation Requests"].includes(label)&&<b>{label==="Orders"&&order?1:0}</b>}</a>)}</nav><nav className="portal-secondary-nav"><a className={kind==="account-details"?"active":""} href="/account/account-details"><i>♙</i><span>Account Details</span></a><a className={kind==="addresses"?"active":""} href="/account/addresses"><i>◆</i><span>Addresses</span></a><a className={kind==="payment-methods"?"active":""} href="/account/payment-methods"><i>▣</i><span>Payment Methods</span></a><button onClick={()=>{localStorage.removeItem("mr-session");window.location.href="/login"}}><i>↪</i><span>Logout</span></button></nav><div className="portal-help"><i>◉</i><h3>Need Help?</h3><p>We are here to help you.</p><a href="/account/support-tickets">Create Ticket</a></div></aside>
    <div className="portal-main"><div className="portal-top"><label><input placeholder="Search your account..." /><span>⌕</span></label><button>♟</button><div className="portal-user"><span>{user.name.charAt(0)}</span><b>{user.name}</b></div></div>
      <header className="portal-section-head"><div className="section-head-icon">{icon}</div><div><span className="eyebrow">Customer account</span><h1>{title}</h1><p>{description}</p></div><a href="/account">Back to dashboard →</a></header>
      {kind==="orders"&&<section className="portal-content-card"><div className="portal-heading"><h2>Order history</h2><span>{order?1:0} order</span></div>{order?<div className="orders-table"><div className="table-head"><span>Order</span><span>Payment</span><span>Total</span><span>Status</span><span></span></div><div className="table-row"><b>{order.number}</b><span>{order.payment}</span><strong>৳ {order.total.toLocaleString("en-US")}</strong><em>{order.status}</em><button>View details</button></div></div>:<Empty icon="▣" title="No orders yet" text="Your purchases will appear here."/>}</section>}
      {kind==="downloads"&&<section className="portal-content-card"><div className="portal-heading"><h2>Available downloads</h2><span>{order?.items?.length||0} products</span></div>{order?.items?.length?order.items.map(item=><div className="download-row" key={item.name}><i>{item.name.charAt(0)}</i><div><b>{item.name}</b><small>{item.variation} · Awaiting activation</small></div><button disabled>Not available yet</button></div>):<Empty icon="↓" title="No downloads available yet" text="Purchased files and product access will appear here after order completion."/>}</section>}
      {kind==="membership"&&<><section className="member-page-hero"><div><span className="eyebrow">Current membership</span><h2>{membership?.level||"Silver"} Member</h2><p>{membership?.next ? <>Spend <b>৳ {remaining.toLocaleString("en-US")}</b> more to unlock {membership.next.name} and {membership.next.discountPercent}% discount.</> : "You have reached the highest membership level."}</p></div><strong>৳ {spent.toLocaleString("en-US")}<small>Lifetime spending</small></strong></section><section className="tier-strip member-page-tiers">{(membership?.tiers||[]).map((tier,i)=>{const next=membership?.tiers[i+1];return <div className={tier.name===membership?.level?"current":""} key={tier.name}><i>{i+1}</i><b>{tier.name}</b><small>{next?`৳${tier.minimumSpend.toLocaleString("en-US")} – ${(next.minimumSpend-1).toLocaleString("en-US")}`:`৳${tier.minimumSpend.toLocaleString("en-US")}+`}</small><strong>{tier.discountPercent}% OFF</strong></div>})}</section><section className="portal-content-card benefit-card"><h2>How membership works</h2><div><span>01<b>Shop normally</b><small>Every completed purchase counts.</small></span><span>02<b>Level up automatically</b><small>Your level follows lifetime spending.</small></span><span>03<b>Save every time</b><small>Discount applies automatically.</small></span></div></section></>}
      {(kind==="support-tickets"||kind==="activation-requests")&&<section className="request-layout"><form className="portal-content-card request-form" onSubmit={submit}><span className="eyebrow">{kind==="support-tickets"?"New support ticket":"New activation request"}</span><h2>{kind==="support-tickets"?"How can we help?":"Request product activation"}</h2><label><span>Subject</span><input required placeholder={kind==="support-tickets"?"Briefly describe the issue":"Product name and website"} /></label><label><span>{kind==="support-tickets"?"Related order":"Product / Order number"}</span><input placeholder="Optional" /></label><label><span>Details</span><textarea required placeholder="Share the information needed to process your request." /></label>{saved&&<p className="request-success">✓ Request submitted successfully.</p>}<button type="submit">Submit request ↗</button></form><aside className="portal-content-card request-aside"><i>{icon}</i><h2>Direct expert support</h2><p>Requests will be reviewed from the customer dashboard. You can track updates here.</p><ul><li>Order-linked assistance</li><li>Clear status updates</li><li>Secure activation process</li></ul></aside></section>}
      {kind==="wishlist"&&<section className="portal-content-card"><div className="portal-heading"><h2>Saved products</h2><span>0 items</span></div><Empty icon="♡" title="Your wishlist is empty" text="Save products while browsing and return to them here."/><div className="empty-action"><a href="/products">Explore products ↗</a></div></section>}
      {kind==="account-details"&&<form className="portal-content-card settings-form" onSubmit={(e)=>{e.preventDefault();const data=new FormData(e.currentTarget),updated={name:String(data.get("name")),email:String(data.get("email")),phone:String(data.get("phone"))};localStorage.setItem("mr-session",JSON.stringify(updated));setUser(updated);setSaved(true)}}><div className="portal-heading"><h2>Personal information</h2><span>Customer profile</span></div><div className="settings-grid"><label><span>Full name</span><input name="name" defaultValue={user.name} required /></label><label><span>Email address</span><input name="email" type="email" defaultValue={user.email} required /></label><label><span>Phone number</span><input name="phone" defaultValue={(user as User&{phone?:string}).phone||""} placeholder="01XXXXXXXXX" /></label><label><span>Display name</span><input defaultValue={user.name} /></label></div>{saved&&<p className="request-success">✓ Account details updated.</p>}<button type="submit">Save changes ↗</button></form>}
      {kind==="addresses"&&<form className="portal-content-card settings-form" onSubmit={(e)=>{e.preventDefault();localStorage.setItem("mr-address",JSON.stringify(Object.fromEntries(new FormData(e.currentTarget))));setSaved(true)}}><div className="portal-heading"><h2>Contact address</h2><span>Optional</span></div><p className="settings-intro">Country and district are not required at checkout. This address is saved only for service communication when needed.</p><div className="settings-grid"><label><span>Address label</span><input name="label" placeholder="Home / Office" /></label><label><span>Contact phone</span><input name="phone" placeholder="01XXXXXXXXX" /></label><label className="wide-setting"><span>Street address</span><input name="address" placeholder="House, road and area" /></label><label><span>City / Area</span><input name="city" placeholder="Dhaka" /></label><label><span>Postcode</span><input name="postcode" placeholder="Optional" /></label></div>{saved&&<p className="request-success">✓ Address saved successfully.</p>}<button type="submit">Save address ↗</button></form>}
      {kind==="payment-methods"&&<section className="portal-content-card"><div className="portal-heading"><h2>Preferred payment method</h2><span>Manual payment</span></div><p className="settings-intro">Select the method you prefer to see first during checkout. No banking credentials are stored here.</p><div className="saved-payment-grid">{[["b","bKash"],["N","Nagad"],["R","Rocket"],["U","Upay"],["P","Pocket"],["B","Bank Transfer"]].map(([ic,name],i)=><button className={saved&&i===0?"selected":""} onClick={()=>setSaved(true)} key={name}><i>{ic}</i><b>{name}</b><small>{i===0&&saved?"Preferred":"Set as preferred"}</small></button>)}</div>{saved&&<p className="request-success">✓ Preferred payment method updated.</p>}</section>}
    </div></div></section><SiteFooter/></main>;
}
function Empty({icon,title,text}:{icon:string;title:string;text:string}){return <div className="section-empty"><i>{icon}</i><h3>{title}</h3><p>{text}</p></div>}
