export type ReadyTheme={id:string;name:string;category:string;status:"Published"|"Draft";price:number;pages:number;rating:number;reviewCount:number;description:string;features:string;information?:string;packageFeatures?:string;packageFeatureMode?:"category"|"custom";demo:string;catalogImage?:string;catalogImageName?:string;detailImage?:string;detailImageName?:string;image?:string;imageName?:string};
export const THEME_STORAGE_KEY="mr-admin-ready-themes";
export const THEME_CATEGORY_STORAGE_KEY="mr-ready-theme-categories";
export const THEME_FAQ_STORAGE_KEY="mr-global-theme-faq";
export const THEME_PACKAGE_STORAGE_KEY="mr-theme-category-package-features";
export const defaultPackageFeatureRows:[string,boolean,boolean,boolean][]=[["Unique Design",true,true,true],["Premium Theme Plugin",true,true,true],["Mobile Friendly",true,true,true],["Photo Gallery",true,true,true],["Video Gallery",true,true,true],["Technical Support",true,true,true],["Search Optimization",false,true,true],["Speed Optimization",false,true,true],["Domain For One Year",false,false,true],["5 GB Hosting For One Year",false,false,true]];
export function encodePackageFeatures(rows:[string,boolean,boolean,boolean][]){return rows.filter(row=>row[0].trim()).map(row=>`${row[0].trim()}|${row[1]?"1":"0"}|${row[2]?"1":"0"}|${row[3]?"1":"0"}`).join("\n")}
export function decodePackageFeatures(value?:string){return (value||encodePackageFeatures(defaultPackageFeatureRows)).split("\n").filter(Boolean).map(row=>{const [label,p1,p2,p3]=row.split("|");return [label,p1==="1",p2==="1",p3!=="0"] as [string,boolean,boolean,boolean]})}
export function loadCategoryPackageFeatures(category:string){if(typeof window==="undefined")return defaultPackageFeatureRows;try{const stored=JSON.parse(localStorage.getItem(THEME_PACKAGE_STORAGE_KEY)||"{}");return decodePackageFeatures(stored[category])}catch{return defaultPackageFeatureRows}}
export function saveCategoryPackageFeatures(category:string,rows:[string,boolean,boolean,boolean][]){const stored=JSON.parse(localStorage.getItem(THEME_PACKAGE_STORAGE_KEY)||"{}");stored[category]=encodePackageFeatures(rows);localStorage.setItem(THEME_PACKAGE_STORAGE_KEY,JSON.stringify(stored));window.dispatchEvent(new Event("mr-theme-packages-updated"))}
export const defaultThemeFaq="Is the theme ready to use?|Yes. Each theme includes the prepared layout and features shown on its details page.\nCan I customize the design?|Yes. Content, colors and essential sections can be customized for your business.\nDoes the theme price include hosting?|No. Domain and hosting are separate unless specifically included in your package.\nWill you install the theme?|Installation and setup follow the service details shown before ordering.\nIs support included?|Yes. The included support period will be shown on the Ready Theme Details page.";
export const seedThemes:ReadyTheme[]=[
  {id:"corporate-pro",name:"Corporate Pro",category:"Business & Agency",status:"Published",price:8500,pages:7,rating:4.9,reviewCount:12,description:"A polished corporate website prepared for modern service businesses and agencies.",features:"Responsive business layout\nService and project sections\nContact and lead forms\nEasy content customization",demo:""},
  {id:"shop-essential",name:"Shop Essential",category:"eCommerce Store",status:"Published",price:12500,pages:9,rating:4.8,reviewCount:9,description:"A conversion-focused eCommerce layout for growing online stores.",features:"Modern product catalogue\nCart and checkout flow\nMobile-ready storefront\nSales-focused sections",demo:""},
  {id:"service-expert",name:"Service Expert",category:"Professional Services",status:"Published",price:7500,pages:6,rating:4.9,reviewCount:7,description:"A compact professional website for consultants and service providers.",features:"Service presentation\nPortfolio section\nCustomer testimonials\nContact integration",demo:""},
  {id:"news-portal",name:"News Portal",category:"Newspaper Themes",status:"Published",price:15000,pages:10,rating:4.9,reviewCount:15,description:"A structured publishing layout for Bangla and English news portals.",features:"Category-based news layout\nBreaking news area\nAdvertisement positions\nMobile reading experience",demo:""},
  {id:"course-academy",name:"Course Academy",category:"School & Colleges",status:"Draft",price:18000,pages:11,rating:4.8,reviewCount:6,description:"An education website layout for courses, institutes and online academies.",features:"Course catalogue\nTeacher profiles\nAdmission information\nStudent-friendly navigation",demo:""},
  {id:"clinic-care",name:"Clinic Care",category:"Hospital & Clinics",status:"Published",price:12000,pages:8,rating:4.9,reviewCount:8,description:"A clear healthcare website for clinics, doctors and diagnostic centres.",features:"Doctor profiles\nDepartment pages\nAppointment request\nEmergency information",demo:""},
];
export function loadThemes():ReadyTheme[]{if(typeof window==="undefined")return seedThemes;try{const stored=JSON.parse(localStorage.getItem(THEME_STORAGE_KEY)||"null");return (Array.isArray(stored)?stored:seedThemes).map((theme:ReadyTheme)=>({...theme,rating:Number(theme.rating??4.9),reviewCount:Number(theme.reviewCount??5),catalogImage:theme.catalogImage||theme.image||"",catalogImageName:theme.catalogImageName||theme.imageName||"",detailImage:theme.detailImage||theme.image||"",detailImageName:theme.detailImageName||theme.imageName||""}))}catch{return seedThemes}}
export function saveThemes(themes:ReadyTheme[]){localStorage.setItem(THEME_STORAGE_KEY,JSON.stringify(themes));window.dispatchEvent(new Event("mr-themes-updated"))}
export function loadThemeCategories(themes:ReadyTheme[]=loadThemes()){const used=themes.map(x=>x.category);if(typeof window==="undefined")return Array.from(new Set(used));try{const stored=JSON.parse(localStorage.getItem(THEME_CATEGORY_STORAGE_KEY)||"[]");return Array.from(new Set([...(Array.isArray(stored)?stored:[]),...used])).filter(Boolean) as string[]}catch{return Array.from(new Set(used))}}
export function saveThemeCategories(categories:string[]){localStorage.setItem(THEME_CATEGORY_STORAGE_KEY,JSON.stringify(Array.from(new Set(categories.filter(Boolean)))))}
export function loadThemeFaq(){if(typeof window==="undefined")return defaultThemeFaq;return localStorage.getItem(THEME_FAQ_STORAGE_KEY)||defaultThemeFaq}
export function saveThemeFaq(faq:string){localStorage.setItem(THEME_FAQ_STORAGE_KEY,faq);window.dispatchEvent(new Event("mr-theme-faq-updated"))}
export function themeSlug(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
