import { customerId, now } from "@/app/customer-auth";
import { getPool } from "@/db";

const text = (value: unknown, max: number) => typeof value === "string" ? value.trim().slice(0, max) : "";
const fields = (body: Record<string, unknown> | null) => ({ label: text(body?.label, 60) || "Address", recipientName: text(body?.recipientName, 100), phone: text(body?.phone, 30), line1: text(body?.line1, 200), line2: text(body?.line2, 200), city: text(body?.city, 100), postcode: text(body?.postcode, 30), country: text(body?.country, 100) || "Bangladesh" });

export async function GET(request: Request) { const customer = customerId(request); if (!customer) return Response.json({ ok: false, error: "Unauthorized." }, { status: 401 }); const result = await getPool().query("SELECT id,label,recipient_name AS \"recipientName\",phone,line1,line2,city,postcode,country,is_default AS \"isDefault\",created_at AS \"createdAt\" FROM customer_addresses WHERE customer_id=$1 ORDER BY is_default DESC,created_at DESC", [customer]); return Response.json({ ok: true, addresses: result.rows }); }
export async function POST(request: Request) { const customer = customerId(request); if (!customer) return Response.json({ ok: false, error: "Unauthorized." }, { status: 401 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null, value = fields(body); if (!value.recipientName || !value.phone || !value.line1 || !value.city) return Response.json({ ok: false, error: "Recipient, phone, address and city are required." }, { status: 400 }); const id = crypto.randomUUID(), timestamp = now(), isDefault = body?.isDefault === true || body?.isDefault === "on"; const client = await getPool().connect(); try { await client.query("BEGIN"); if (isDefault) await client.query("UPDATE customer_addresses SET is_default=false WHERE customer_id=$1", [customer]); await client.query("INSERT INTO customer_addresses (id,customer_id,label,recipient_name,phone,line1,line2,city,postcode,country,is_default,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12)", [id, customer, value.label, value.recipientName, value.phone, value.line1, value.line2, value.city, value.postcode, value.country, isDefault, timestamp]); await client.query("COMMIT"); return Response.json({ ok: true, message: "Address saved." }, { status: 201 }); } catch { await client.query("ROLLBACK").catch(() => undefined); return Response.json({ ok: false, error: "Address could not be saved." }, { status: 500 }); } finally { client.release(); } }
export async function DELETE(request: Request) { const customer = customerId(request), id = new URL(request.url).searchParams.get("id") || ""; if (!customer) return Response.json({ ok: false, error: "Unauthorized." }, { status: 401 }); await getPool().query("DELETE FROM customer_addresses WHERE id=$1 AND customer_id=$2", [id, customer]); return Response.json({ ok: true }); }
